### ISSUE TITLE
ImportError: ./ibm_db_dlls\ibm_db.dll: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rossj-cargotel** [ibmdb/python-ibmdb#185]
On
```
[rossj@717311-app1 ibm_db-2.0.5.1]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)
```
I can apparently build the ibm_db driver but can't import it.
```
[rossj@717311-app1 ibm_db-2.0.5.1]$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibm_db.py", line 7, in <module>
    __bootstrap__()
  File "ibm_db.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
ImportError: ./ibm_db_dlls\ibm_db.dll: cannot open shared object file: No such file or directory
```
The dsdriver package is installed in /opt/IBM/informix and I've sourced the db2profle:

```
. /opt/IBM/informix/dsdriver/db2profile
```
I do get this in the initial build:
```
rossj@717311-app1 ibm_db-2.0.5.1]$ sudo python setup.py install
Detected 64-bit Python
running install
running bdist_egg
running egg_info
writing ibm_db.egg-info/PKG-INFO
writing top-level names to ibm_db.egg-info/top_level.txt
writing dependency_links to ibm_db.egg-info/dependency_links.txt
reading manifest file 'ibm_db.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'ibm_db_dlls'
writing manifest file 'ibm_db.egg-info/SOURCES.txt'
```
I've also tried building through easy-install with the same results.

Any suggestions?
Jeff

**Comment by rossj-cargotel** [comment]
I'm marking this as closed.  I'm not sure what changed but now everything is working fine.
