### ISSUE TITLE
Irregular DatabaseError seen when using Django

### ISSUE THREAD

**Issue by mjlawrence83** [ibmdb/python-ibmdb#191]
When running selenium tests in Django via an Ant build script, one in every ten runs the following error is encountered, which causes the test to fail, is there a known resolution?:

File "/usr/lib64/python2.6/site-packages/django/db/models/manager.py", line 151, in get
     [exec]     return self.get_queryset().get(*args, **kwargs)
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/query.py", line 304, in get
     [exec]     num = len(clone)
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/query.py", line 77, in __len__
     [exec]     self._fetch_all()
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/query.py", line 857, in _fetch_all
     [exec]     self._result_cache = list(self.iterator())
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/query.py", line 220, in iterator
     [exec]     for row in compiler.results_iter():
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
     [exec]     for rows in self.execute_sql(MULTI):
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/models/sql/compiler.py", line 800, in <lambda>
     [exec]     result = iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/utils.py", line 106, in inner
     [exec]     return func(*args, **kwargs)
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
     [exec]     six.reraise(dj_exc_type, dj_exc_value, traceback)
     [exec]   File "/usr/lib64/python2.6/site-packages/django/db/utils.py", line 106, in inner
     [exec]     return func(*args, **kwargs)
     [exec]   File "/usr/lib/python2.6/site-packages/ibm_db_django-1.0.7-py2.6.egg/ibm_db_django/pybase.py", line 224, in fetchmany
     [exec]     rows = super( DB2CursorWrapper, self ).fetchmany( size )
     [exec]   File "/usr/lib64/python2.6/site-packages/ibm_db_dbi.py", line 1454, in fetchmany
     [exec]     return self._fetch_helper(size)
     [exec]   File "/usr/lib64/python2.6/site-packages/ibm_db_dbi.py", line 1417, in _fetch_helper
     [exec]     raise self.messages[len(self.messages) - 1]
     [exec] DatabaseError

**Comment by mjlawrence83** [comment]
I have additionally encountered this similar error when calling a JSON data providing function:

   if not request.user.is_authenticated():
File "/usr/lib64/python2.6/site-packages/django/utils/functional.py" in inner
  213.             self._setup()
File "/usr/lib64/python2.6/site-packages/django/utils/functional.py" in _setup
  298.         self._wrapped = self._setupfunc()
File "/usr/lib64/python2.6/site-packages/django/contrib/auth/middleware.py" in <lambda>
  18.         request.user = SimpleLazyObject(lambda: get_user(request))
File "/usr/lib64/python2.6/site-packages/django/contrib/auth/middleware.py" in get_user
  10.         request._cached_user = auth.get_user(request)
File "/usr/lib64/python2.6/site-packages/django/contrib/auth/__init__.py" in get_user
  140.         user_id = request.session[SESSION_KEY]
File "/usr/lib64/python2.6/site-packages/django/contrib/sessions/backends/base.py" in __getitem__
  47.         return self._session[key]
File "/usr/lib64/python2.6/site-packages/django/contrib/sessions/backends/base.py" in _get_session
  173.                 self._session_cache = self.load()
File "/usr/lib64/python2.6/site-packages/django/contrib/sessions/backends/db.py" in load
  20.                 expire_date__gt=timezone.now()
File "/usr/lib64/python2.6/site-packages/django/db/models/manager.py" in get
  151.         return self.get_queryset().get(*args, **kwargs)
File "/usr/lib64/python2.6/site-packages/django/db/models/query.py" in get
  304.         num = len(clone)
File "/usr/lib64/python2.6/site-packages/django/db/models/query.py" in __len__
  77.         self._fetch_all()
File "/usr/lib64/python2.6/site-packages/django/db/models/query.py" in _fetch_all
  857.             self._result_cache = list(self.iterator())
File "/usr/lib64/python2.6/site-packages/django/db/models/query.py" in iterator
  220.         for row in compiler.results_iter():
File "/usr/lib64/python2.6/site-packages/django/db/models/sql/compiler.py" in results_iter
  713.         for rows in self.execute_sql(MULTI):
File "/usr/lib64/python2.6/site-packages/django/db/models/sql/compiler.py" in execute_sql
  806.             return list(result)
File "/usr/lib64/python2.6/site-packages/django/db/models/sql/compiler.py" in <lambda>
  800.             result = iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
File "/usr/lib64/python2.6/site-packages/django/db/utils.py" in inner
  106.                 return func(*args, **kwargs)
File "/usr/lib64/python2.6/site-packages/django/db/utils.py" in __exit__
  99.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/lib64/python2.6/site-packages/django/db/utils.py" in inner
  106.                 return func(*args, **kwargs)
File "/usr/lib/python2.6/site-packages/ibm_db_django/pybase.py" in fetchmany
  224.         rows = super( DB2CursorWrapper, self ).fetchmany( size )
File "/usr/lib/python2.6/site-packages/ibm_db-2.0.5-py2.6-linux-x86_64.egg/ibm_db_dbi.py" in fetchmany

  1454.         return self._fetch_helper(size)
File "/usr/lib/python2.6/site-packages/ibm_db-2.0.5-py2.6-linux-x86_64.egg/ibm_db_dbi.py" in _fetch_helper

  1417.                     raise self.messages[len(self.messages) - 1]

Exception Type: DatabaseError

**Comment by mjlawrence83** [comment]
Another error seen:

[10/Nov/2015 11:36:00] "GET /customer/getImtChoicesJSON/59/ HTTP/1.1" 500 17180
Traceback (most recent call last):
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 94, in run
    self.finish_response()
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 137, in finish_response
    self.close()
  File "/usr/lib64/python2.6/wsgiref/simple_server.py", line 36, in close
    SimpleHandler.close(self)
  File "/usr/lib64/python2.6/wsgiref/handlers.py", line 263, in close
    self.result.close()
  File "/usr/lib64/python2.6/site-packages/django/http/response.py", line 305, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/lib64/python2.6/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib64/python2.6/site-packages/django/db/__init__.py", line 94, in close_old_connections
    conn.close_if_unusable_or_obsolete()
  File "/usr/lib64/python2.6/site-packages/django/db/backends/__init__.py", line 474, in close_if_unusable_or_obsolete
    if self.is_usable():
  File "/usr/lib/python2.6/site-packages/ibm_db_django/base.py", line 240, in is_usable
    if self.databaseWrapper.is_active(connection):
NameError: global name 'connection' is not defined

**Comment by mjlawrence83** [comment]
Another error seen:

[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     return self.get_queryset().get(*args, **kwargs)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 304, in get
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     num = len(clone)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 77, in __len__
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self._fetch_all()
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 857, in _fetch_all
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self._result_cache = list(self.iterator())
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 220, in iterator
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     for row in compiler.results_iter():
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     for rows in self.execute_sql(MULTI):
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     cursor = self.connection.cursor()
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 162, in cursor
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     cursor = util.CursorWrapper(self._cursor(), self)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 132, in _cursor
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self.ensure_connection()
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self.connect()
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     six.reraise(dj_exc_type, dj_exc_value, traceback)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 127, in ensure_connection
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self.connect()
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/django/db/backends/__init__.py", line 115, in connect
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     self.connection = self.get_new_connection(conn_params)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/ibm_db_django/base.py", line 223, in get_new_connection
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     connection = self.databaseWrapper.get_new_connection(conn_params)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib/python2.6/site-packages/ibm_db_django/pybase.py", line 84, in get_new_connection
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     connection = Database.pconnect( **kwargs )
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]   File "/usr/lib64/python2.6/site-packages/ibm_db_dbi.py", line 637, in pconnect
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239]     raise _get_exception(inst)
[Mon Oct 05 08:56:49 2015] [error] [client 90.206.161.239] OperationalError

**Comment by jospaul1** [comment]
Can you please try this with Python 2.7 ?.This should be some environment  issue ,the last trace says that even new connection call is also giving this exception .
Can we replicate this in a simple test case ?.

**Comment by mjlawrence83** [comment]
Hi,

I've created a new VM environment today using RHEL7.1 (Python 2.7), but the error still remains. I also tried updating to ibm-db v2.0.6 & ibm-db-django v1.0.7, but without success. The exception below was encountered almost immediately, however the problem is not easily repeatable, its seen in several different scenarios, and isn't reliably replicated.

For one scenario it happens 1 in 15 times. We have a web page containing three dependent dropdown's. On the selection of a country in one of the dropdowns, the IOT and IMT dropdowns are populated. These are populated using Dojo's ItemFileReadStore's ability to fetch data asynchronously via a URL (/customer/getImtChoicesJSON/2/). The function associated with this URL then checks to see if the user is authenticated (where the below exception is thrown) and data for the dropdowns are returned.

What would be the next step in trying to resolve this?


[11/Nov/2015 16:59:31] "GET /customer/getImtChoicesJSON/2/ HTTP/1.1" 200 95
ERROR - Internal Server Error: /customer/getIotChoicesJSON/2/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 88, in get_response
    response = middleware_method(request)
  File "/home/mark/workspace/bfly.backup.selfservice/self_service/selfservice/ssmiddleware.py", line 28, in process_request
    if not request.user.is_authenticated():
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 213, in inner
    self._setup()
  File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 298, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 144, in get_user
    user = backend.get_user(user_id) or AnonymousUser()
  File "/home/mark/workspace/bfly.backup.selfservice/self_service/selfservice/ssbackend.py", line 69, in get_user
    return get_user_model().objects.get(pk=user_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 800, in <lambda>
    result = iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 106, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 106, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ibm_db_django/pybase.py", line 224, in fetchmany
    rows = super( DB2CursorWrapper, self ).fetchmany( size )
  File "/usr/lib64/python2.7/site-packages/ibm_db_dbi.py", line 1455, in fetchmany
    return self._fetch_helper(size)
  File "/usr/lib64/python2.7/site-packages/ibm_db_dbi.py", line 1418, in _fetch_helper
    raise self.messages[len(self.messages) - 1]
DatabaseError

**Comment by mjlawrence83** [comment]
I have also upgraded to Django 1.7, but the issue still remains.

**Comment by jospaul1** [comment]
Please try installing from https://github.com/ibmdb/python-ibmdb .
You can download the zip and install from that .
bcrypt (2.0.0)
cffi (1.1.2)
Django (1.7)
django-binaryfield (0.4.0)
docutils (0.12)
funcsigs (0.4)
ibm-db (2.0.5.1)
ibm-db-django (1.0.7)
ibm-db-sa (0.3.2)
Jinja2 (2.7.3)
MarkupSafe (0.23)
mock (1.2.0)
mysql-connector-python (2.0.4)
mysql-python (1.2.5)
numpy (1.9.2)
pbr (1.3.0)
Pillow (2.9.0)
pip (7.0.1)
pycparser (2.14)
python-memcached (1.54)
pytz (2015.4)
PyYAML (3.11)
selenium (2.46.1)
setuptools (17.1.1)
six (1.9.0)
South (1.0.2)
SQLAlchemy (1.0.8)
sqlparse (0.1.15)

This is my "pip list " output .Please make sure that you have Django 1.7.x .

**Comment by mjlawrence83** [comment]
Hi,

I've installed both ibm-db and ibm-db-django from the GitHub zip and ensured the version of my installed packages are the same as the ones listed in your pip list, but I am still experiencing the same exceptions.

It's likely I will need to create a new django project which will recreate this issue. Is this the best approach? Shall I just zip it up and post within this thread?

**Comment by mjlawrence83** [comment]
Whilst creating the project to recreate the exception, I've found that the problems only occur when the PCONNECT db option setting is True. When False, no exceptions occur.
A persistent connection is required in our production scenario because the Django server and DB2 server are different machines, not having a persistent connection reduces performance dramatically.

**Comment by jospaul1** [comment]
http://grokbase.com/p/gg/django-developers/132kex8f8b/database-pooling-vs-persistent-connections
Are you using PCONNECT in a multithreaded environment ?.
It is not expected to use in such environment .Please let me know .

**Comment by mjlawrence83** [comment]
I've now created a dummy project, which recreates the issue. This project is designed to run with Django's built-in test web server, and uses single requests. So this problem is being seen in a single threaded environment.
Do you have an IBM email/Box so I can send the project to you so you can see the problem?

**Comment by mjlawrence83** [comment]
Problem resolved, Django's CONN_MAX_AGE must be set to None for persistent connections
