### ISSUE TITLE
ibm_db_django 1.1.0.0: exception when attempting to apply auth migration

### ISSUE THREAD

**Issue by nhardman** [ibmdb/python-ibmdb#243]
Exception raised when running python manage.py migrate auth:

my environment first....

pip list --format=columns | grep ibm
ibm-db                             2.0.7  
ibm-db-django                      1.1.0.0

pip list --format=columns | grep Django
Django 1.8.16

```
Operations to perform:
  Apply all migrations: auth
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/lib/python2.7/site-packages/ibm_db_django-1.1.0.0-py2.7.egg/ibm_db_django/schemaEditor.py", line 129, in alter_field
    rel_condition = (old_field.rel.through and new_field.rel.through and old_field.rel.through._meta.auto_created and new_field.rel.through._meta.auto_created)
AttributeError: 'NoneType' object has no attribute 'through'
```

From the actual code. (schemaEditor.py)....
```
if( djangoVersion[0:2] < ( 1, 9 ) ):
    rel_condition = (old_field.rel.through and new_field.rel.through and ld_field.rel.through._meta.auto_created and new_field.rel.through._meta.auto_created)
    else:
        if old_field.remote_field is not None and hasattr(old_field.remote_field,'through'):
            rel_condition = (old_field.remote_field.through and new_field.remote_field.through and old_field.remote_field.through._meta.auto_created and new_field.remote_field.through._meta.auto_created)
        else:
            rel_condition = False
```
It looks like there needs to be guard test to prevent the exception:

```
    if( djangoVersion[0:2] < ( 1, 9 ) ):
        if old_field.rel is not None and hasattr(old_field.rel,'through'):
            rel_condition = (old_field.rel.through and new_field.rel.through and old_field.rel.through._meta.auto_created and new_field.rel.through._meta.auto_created)
        else:
            rel_condition = False
    else:
        if old_field.remote_field is not None and hasattr(old_field.remote_field,'through'):
            rel_condition = (old_field.remote_field.through and new_field.remote_field.through and old_field.remote_field.through._meta.auto_created and new_field.remote_field.through._meta.auto_created)
        else:
            rel_condition = False
```

**Comment by hemlatabhatt** [comment]
Hi,
This is now fixed in git-hub .Please use the latest code.

Thanks for reporting the issue.
