### ISSUE TITLE
bulk_insert_sql exception

### ISSUE THREAD

**Issue by nhardman** [ibmdb/python-ibmdb#244]
The bulk_insert method in operations.py raises and exception because it attempts an invalid len() operation on an integer variable **num_values**. It looks like it was assuming that num_values was a list (or some other iterable object):

My environment:

pip list --format=columns | grep ibm
ibm-db                             2.0.7  
ibm-db-django                 1.1.0.0

pip list --format=columns | grep Django
Django                             1.8.16

```
[Mon Nov 28 11:38:29.219036 2016] [:error] [pid 3921] [28/Nov/2016 11:38:29] ERROR [django.request:256] Internal Server Error: /account/login/
[Mon Nov 28 11:38:29.219081 2016] [:error] [pid 3921] Traceback (most recent call last):
[Mon Nov 28 11:38:29.219088 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
[Mon Nov 28 11:38:29.219092 2016] [:error] [pid 3921]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Nov 28 11:38:29.219097 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
[Mon Nov 28 11:38:29.219101 2016] [:error] [pid 3921]     return view(request, *args, **kwargs)
[Mon Nov 28 11:38:29.219105 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 110, in _wrapped_view
[Mon Nov 28 11:38:29.219109 2016] [:error] [pid 3921]     response = view_func(request, *args, **kwargs)
[Mon Nov 28 11:38:29.219113 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
[Mon Nov 28 11:38:29.219117 2016] [:error] [pid 3921]     response = view_func(request, *args, **kwargs)
[Mon Nov 28 11:38:29.219121 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/contrib/auth/views.py", line 51, in login
[Mon Nov 28 11:38:29.219125 2016] [:error] [pid 3921]     auth_login(request, form.get_user())
[Mon Nov 28 11:38:29.219129 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/contrib/auth/__init__.py", line 110, in login
[Mon Nov 28 11:38:29.219133 2016] [:error] [pid 3921]     request.session.cycle_key()
[Mon Nov 28 11:38:29.219137 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/contrib/sessions/backends/base.py", line 285, in cycle_key
[Mon Nov 28 11:38:29.219152 2016] [:error] [pid 3921]     self.create()
[Mon Nov 28 11:38:29.219157 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/contrib/sessions/backends/db.py", line 41, in create
[Mon Nov 28 11:38:29.219161 2016] [:error] [pid 3921]     self.save(must_create=True)
[Mon Nov 28 11:38:29.219164 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/contrib/sessions/backends/db.py", line 65, in save
[Mon Nov 28 11:38:29.219168 2016] [:error] [pid 3921]     obj.save(force_insert=must_create, using=using)
[Mon Nov 28 11:38:29.219171 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 734, in save
[Mon Nov 28 11:38:29.219175 2016] [:error] [pid 3921]     force_update=force_update, update_fields=update_fields)
[Mon Nov 28 11:38:29.219178 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 762, in save_base
[Mon Nov 28 11:38:29.219181 2016] [:error] [pid 3921]     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
[Mon Nov 28 11:38:29.219185 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 846, in _save_table
[Mon Nov 28 11:38:29.219188 2016] [:error] [pid 3921]     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[Mon Nov 28 11:38:29.219192 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/base.py", line 885, in _do_insert
[Mon Nov 28 11:38:29.219195 2016] [:error] [pid 3921]     using=using, raw=raw)
[Mon Nov 28 11:38:29.219199 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/manager.py", line 127, in manager_method
[Mon Nov 28 11:38:29.219202 2016] [:error] [pid 3921]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Mon Nov 28 11:38:29.219205 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/query.py", line 920, in _insert
[Mon Nov 28 11:38:29.219209 2016] [:error] [pid 3921]     return query.get_compiler(using=using).execute_sql(return_id)
[Mon Nov 28 11:38:29.219212 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/sql/compiler.py", line 973, in execute_sql
[Mon Nov 28 11:38:29.219216 2016] [:error] [pid 3921]     for sql, params in self.as_sql():
[Mon Nov 28 11:38:29.219219 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/Django-1.8.16-py2.7.egg/django/db/models/sql/compiler.py", line 961, in as_sql
[Mon Nov 28 11:38:29.219223 2016] [:error] [pid 3921]     result.append(self.connection.ops.bulk_insert_sql(fields, len(values)))
[Mon Nov 28 11:38:29.219226 2016] [:error] [pid 3921]   File "/usr/lib/python2.7/site-packages/ibm_db_django-1.1.0.0-py2.7.egg/ibm_db_django/operations.py", line 545, in bulk_insert_sql
[Mon Nov 28 11:38:29.219230 2016] [:error] [pid 3921]     bulk_values_sql = "VALUES " + ", ".join([values_sql] * len(num_values) )
[Mon Nov 28 11:38:29.219233 2016] [:error] [pid 3921] TypeError: object of type 'int' has no len()
```

The following code which replaces **len(num_values)** with **num_values** and should fix the issue:
```
    def bulk_insert_sql(self, fields, num_values):
        values_sql = "( %s )" %(", ".join( ["%s"] * len(fields)))
        bulk_values_sql = "VALUES " + ", ".join([values_sql] * num_values )
        return bulk_values_sql
```

**Comment by hemlatabhatt** [comment]
Hi,
This is now fixed in git-hub .Please use the latest code.
Thanks for reporting the issue.

**Comment by mjlawrence83** [comment]
When is the next release containing this fix likely to be?

**Comment by SabaKauser** [comment]
new release will be out shortly.
