### ISSUE TITLE
Error when running post_migrate signal

### ISSUE THREAD

**Issue by mjlawrence83** [ibmdb/python-ibmdb#246]
We are running Django v.1.7.11, and have a piece of code that runs on the post_migrate signal. This runs perfectly fine on ibm-db-django v1.0.7, but v1.0.9.2, and v.1.1.0.0 the following error occurs when running 'migrate':

[root@oc0183805434 self_service]# ./manage.py migrate
Operations to perform:
  Apply all migrations: contenttypes, aer_models, auth, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying aer_models.0001_initial... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib64/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib64/python2.7/site-packages/django/core/management/commands/migrate.py", line 165, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/usr/lib64/python2.7/site-packages/django/core/management/sql.py", line 268, in emit_post_migrate_signal
    using=db)
  File "/usr/lib64/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib64/python2.7/site-packages/django/contrib/auth/management/__init__.py", line 114, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
    self._batched_insert(objs_without_pk, fields, batch_size)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
    using=self.db)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 908, in as_sql
    result.append(self.connection.ops.bulk_insert_sql(fields, len(values)))
  File "/usr/lib/python2.7/site-packages/ibm_db_django/operations.py", line 545, in bulk_insert_sql
    bulk_values_sql = "VALUES " + ", ".join([values_sql] * len(num_values) )
TypeError: object of type 'int' has no len()

**Comment by nhardman** [comment]
This is the same issue as #244
