### ISSUE TITLE
Missing DB2 View "SYSCAT"."TABLES" When Uploading DataFrame to DB2

### ISSUE THREAD

**Issue by octopyth** [ibmdb/python-ibmdb#255]
I am attempting to upload pandas dataframe to db2 database with ibm_db_sa driver in Python3, when I get an error for missing view "SYSCAT"."TABLES". Is it a matter of select privilege to the view? If not is it possible to skip the check for existence of the destination table in the view "SYSCAT"."TABLES"?

>>> import pandas as pd
>>> import sqlalchemy
>>> from sqlalchemy import select, create_engine
>>> import ibm_db_sa

>>> engine = create_engine('...')
>>> sql = 'select * from table1'
>>> df = pd.read_sql(sql, engine)

>>> df.to_sql('table2', engine, if_exists='replace')

Traceback (most recent call last):
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_dbi.py", line 1215, in _set_cursor_helper
    num_columns = ibm_db.num_fields(self.stmt_handler)
Exception: SQLNumResultCols failed: [IBM][CLI Driver][DB2] SQL0204N  "SYSCAT.TABLES" is an undefined name.  SQLSTATE=42704
 SQLCODE=-204

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_sa\ibm_db.py", line 107, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_dbi.py", line 1335, in execute
    self._set_cursor_helper()
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_dbi.py", line 1218, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2] SQL0204N  "SYSCAT.TABLES" is an undefined name.  SQLSTATE=42704\r SQLCODE=-204

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\core\generic.py", line 1201, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\sql.py", line 470, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\sql.py", line 1147, in to_sql
    table.create()
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\sql.py", line 584, in create
    if self.exists():
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\sql.py", line 572, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\sql.py", line 1175, in has_table
    schema or self.meta.schema,
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 2036, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1525, in run_callable
    return callable_(self, *args, **kwargs)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_sa\base.py", line 709, in has_table
    return self._reflector.has_table(connection, table_name, schema=schema)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_sa\reflection.py", line 171, in has_table
    c = connection.execute(s)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_sa\ibm_db.py", line 107, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_dbi.py", line 1335, in execute
    self._set_cursor_helper()
  File "C:\Users\SZ\AppData\Local\Programs\Python\Python35\lib\site-packages\ibm_db_dbi.py", line 1218, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: SQLNumResultCols failed: [IBM][CLI Driver][DB2] SQL0204N  "SYSCAT.TABLES" is an undefined name.  SQLSTATE=42704\r SQLCODE=-204 [SQL: 'SELECT "SYSCAT"."TABLES"."TABNAME" \nFROM "SYSCAT"."TABLES" \nWHERE "SYSCAT"."TABLES"."TABSCHEMA" = ? AND "SYSCAT"."TABLES"."TABNAME" = ?'] [parameters: (b'username', b'table2')]

**Comment by hemlatabhatt** [comment]
I  tried using df.to_sql('table2',con= engine, if_exists='replace',index= False) against db2  LUW server and its working for me.
Can you specify which DB server you are using?
