### ISSUE TITLE
ibm_db_django breaks with Django 1.11

### ISSUE THREAD

**Issue by genomics-geek** [ibmdb/python-ibmdb#262]
When I use ibm_db_django with Django 1.11 I observe this error:

```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1069b66a8>
Traceback (most recent call last):
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/db/models/base.py", line 1284, in check
    errors.extend(cls._check_long_column_names())
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/db/models/base.py", line 1699, in _check_long_column_names
    connection = connections[db]
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/db/utils.py", line 212, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/ibm_db_django/base.py", line 155, in __init__
    super( DatabaseWrapper, self ).__init__( *args )
  File "/Users/gonzalezma/.pyenv/versions/django-variant-annotations/lib/python3.5/site-packages/django/db/backends/base/base.py", line 96, in __init__
    self.client = self.client_class(self)
TypeError: 'NoneType' object is not callable
```

However, if I downgrade to Django 1.10.7, this error goes away.

**Comment by juztin** [comment]
I've run across the same issue during an upgrade of packages, including Django/DB2.  

I can get past the above error by adding the below as class variables of `DatabaseWrapper`, in `ibm_db_django/base.py`:

```python
...
    client_class = DatabaseClient
    creation_class = DatabaseCreation
    features_class = DatabaseFeatures
    introspection_class = DatabaseIntrospection
    validation_class = DatabaseValidation
    ops_class = DatabaseOperations
...
```

Along with adding the kwarg `name=None` to the `create_cursor` method:

```python
# From this
def create_cursor( self )

# Top this
def create_cursor( self, name = None )

**Comment by juztin** [comment]
Not 100% sure if the above is the "correct" fix, but I've created PR #263.

**Comment by klada** [comment]
The fix in PR #263 is working for me. Thanks.

**Comment by kadler** [comment]
This issue was moved to ibmdb/python-ibmdb-django#3

**Comment by SabaKauser** [comment]
We will include https://github.com/ibmdb/python-ibmdb/pull/263/commits/b53e1fa31b42fe51eb2f58c196df8f41cd94a22c in upcoming release of ibm_db_django with django 2.0 support.
