### ISSUE TITLE
Version 2.0.8 does not install on python3

### ISSUE THREAD

**Issue by pokoli** [ibmdb/python-ibmdb#286]
```
(test) sergi@portatil ~ ○ » python -V
Python 3.5.2
(test) sergi@portatil ~ ○ » pip install ibm_db                                                                                                                      
Collecting ibm_db
  Downloading ibm_db-2.0.8.tar.gz (689kB)
    100% |████████████████████████████████| 696kB 1.3MB/s 
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... error
  Complete output from command /home/sergi/.virtualenvs/test/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zi7ho5iy/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpv4c_20tppip-wheel- --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-zi7ho5iy/ibm-db/setup.py", line 17, in <module>
      os.rename('tests','test_2')
  OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
  
  ----------------------------------------
  Failed building wheel for ibm-db
  Running setup.py clean for ibm-db
  Complete output from command /home/sergi/.virtualenvs/test/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zi7ho5iy/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-zi7ho5iy/ibm-db/setup.py", line 17, in <module>
      os.rename('tests','test_2')
  OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
  
  ----------------------------------------
  Failed cleaning build dir for ibm-db
Failed to build ibm-db
Installing collected packages: ibm-db
  Running setup.py install for ibm-db ... error
    Complete output from command /home/sergi/.virtualenvs/test/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zi7ho5iy/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2n_1i2qx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/sergi/.virtualenvs/test/include/site/python3.5/ibm-db:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zi7ho5iy/ibm-db/setup.py", line 17, in <module>
        os.rename('tests','test_2')
    OSError: [Errno 39] Directory not empty: 'tests' -> 'test_2'
    
    ----------------------------------------
Command "/home/sergi/.virtualenvs/test/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zi7ho5iy/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2n_1i2qx-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/sergi/.virtualenvs/test/include/site/python3.5/ibm-db" failed with error code 1 in /tmp/pip-build-zi7ho5iy/ibm-db/
```

Everything works well on previous version: 

```
(test) sergi@portatil ~ ○ » pip install "ibm_db<2.0.8"                                                                                                              
Collecting ibm_db<2.0.8
  Using cached ibm_db-2.0.7.tar.gz
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... done
  Stored in directory: /home/sergi/.cache/pip/wheels/d7/05/e2/d7b2f153bfbabcdf8af0fec36d78656142b5966cf6be091af3
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-2.0.7
```

**Comment by pokoli** [comment]
Introduced on 7c3d45b6692412fb30f3ab28b11bd7009218d8bb which renames the tests folders on setup.py.

Don't know why this is required, but probably those lines should be deleted. Shal I propose a PR?

**Comment by SabaKauser** [comment]
This is fixed in pypi. Can you please test.

**Comment by pokoli** [comment]
I sucessfully installed ibm-db-2.0.8a0 on python3 without problems.

**Comment by Cogito** [comment]
Not sure what is going on here, but seeing a very similar issue on 2.0.8

```
$ pip install "ibm_db"
Collecting ibm_db
  Using cached ibm_db-2.0.8.tar.gz
Installing collected packages: ibm-db
  Running setup.py install for ibm-db ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\user\\AppData\\Local\\Temp\\pip-build-buasp3yj\\ibm-db\\setup.py';f=getattr(tokenize, 'open', op
en)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\user\AppData\Local\Temp\pip-qv_zerxn-record\install-record.txt --single-version-externally-managed
--compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-buasp3yj\ibm-db\setup.py", line 17, in <module>
        os.rename('tests','test_2')
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'tests' -> 'test_2'
```

**Comment by natashadsilva** [comment]
+1 Running into this problem as well. I would also add the issue about needing to set the DYLD_LIBRARY_PATH to the README as it is an issue for Mac.

**Comment by SabaKauser** [comment]
for now, please try "pip install ibm_db==2.0.8a". The versions will be incremented for next release.

**Comment by parichaya** [comment]
Hi, 
Even with version 2.0.8a, cannot install on Python 3.5 or Python 3.6 on Ubuntu 16.04.3 LTS.
"....
Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'ibm_db' extension
    creating build/temp.linux-x86_64-3.6
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iclidriver/include -I/usr/include/python3.6m -I/home/parichay/code/env/DB2x.rev2/include/python3.6m -c ibm_db.c -o build/temp.linux-x86_64-3.6/ibm_db.o
    ibm_db.c:27:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
..."
If you do need any debug info. from me, please do feel free to reach out at: parichay@sg.ibm.com - I am happy to help if it enables faster resolution of issue.

**Comment by SabaKauser** [comment]
you does not seem to have Python dev package that contains Python.h.
check these: 
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
https://stackoverflow.com/questions/12379929/cant-find-python-h-file-on-centos/33062410#33062410

**Comment by abirone** [comment]
+1 to this issue. Using 2.0.8a solved the problem.

**Comment by parichaya** [comment]
Thanks SabaKauser for your reply. I think I do have Python Dev package for my Python 3.5 installed, but I will confirm and try again, and will then post an update accordingly.

**Comment by pokoli** [comment]
Could you please upload a new relase including this changes? It's a bit frustrating to always have to install an older version on python3 due to this error

**Comment by shaikShehanaaz** [comment]
Config.py file contains the connection parameters. Removing sample strings and giving my database details solved my error.
