### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by seanhu24** [ibmdb/python-ibmdb#293]
I installed packages as below:
Django (2.0)
django-bootstrap3 (9.1.0)
ibm-db (2.0.7)
ibm-db-django (1.1.1.2)
mysqlclient (1.3.12)
pip (9.0.1)
pytz (2017.3)
setuptools (38.2.4)
wheel (0.30.0)
xlrd (1.1.0)

and setup the config as:
DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'anlybi',
        'HOST': '21.32.121.117',
        'USER': 'anlyusr',
        'PASSWORD': '*****',
        'PORT': 50000,
    }

when running magrate got following error:
`
python manage.py makemigrations upload
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/utils.py", line 203, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/ibm_db_django/base.py", line 155, in __init__
    super( DatabaseWrapper, self ).__init__( *args )
  File "/home/anlyusr/py_script/CCenterEnv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 101, in __init__
    self.client = self.client_class(self)
TypeError: 'NoneType' object is not callable

`

I am using DB2 10.5

**Comment by hemlatabhatt** [comment]
@seanhu24 , Django 2.0 support is not there for ibm_db_django,work is in progress to provide the same.

**Comment by Arlington1985** [comment]
Problem still exist?

**Comment by hemlatabhatt** [comment]
@Arlington1985  ,Please use the latest released version of ibm_db_django (1.2.0.0) which has addressed these issues.If any issues please open here 
https://github.com/ibmdb/python-ibmdb-django/issues
