### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by mejaz** [ibmdb/python-ibmdb#300]
Hello,
I was able to successfully install `ibm-db-2.0.8a0`, but it gives an error when I import `ibm_db` in my python code -- version 3.6

Error is below:
```
 >>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\ibm_db.py", line 10, in <module>
    __bootstrap__()
  File "C:\Python36\lib\site-packages\ibm_db.py", line 9, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Python36\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

Can you suggest on the issue.
I am working in Windows 7 - 64bit

thank you.

**Comment by SabaKauser** [comment]
Hoping that you were able to resolve this, closing. reopen if you need further assistance.

**Comment by snvkgram** [comment]
I am getting the same above error! But I am using python 2.7. 
I have installed it using easy_install and I can find it in site_packages folder. 

When the I execute a python program, it fails at import ibm_db statement with below error:

(virtualenv) C:\Ram\work-ibm\git-repos\scripts>python2 es_daily_report.py
Traceback (most recent call last):
  File "es_daily_report.py", line 11, in <module>
    import ibm_db
  File "C:\Ram\work-ibm\git-repos\scripts\virtualenv\Lib\site-packages\ibm_db-2.0.8-py3.6.egg\ibm_db.py", line 10, in <module>
    __bootstrap__()
  File "C:\Ram\work-ibm\git-repos\scripts\virtualenv\Lib\site-packages\ibm_db-2.0.8-py3.6.egg\ibm_db.py", line 9, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
ImportError: DLL load failed: %1 is not a valid Win32 application.

It started troubling after a system reboot.
OS is Windows 7 - 64 bit.

**Comment by anky1987git** [comment]
I am also getting same error. Didn't see any resolution posted above. Anyone knows the reason?

**Comment by snvkgram** [comment]
Hi, I vaguely remember that I have removed the egg file and re-installed it. Don’t forget to use python2 or pip2 while installing. Good luck.

**Comment by SabaKauser** [comment]
If you are using python 2.7, I do not expect it to use python 3.6 egg
File "C:\Ram\work-ibm\git-repos\scripts\virtualenv\Lib\site-packages\ibm_db-2.0.8-**py3.6.egg**\ibm_db.py", line 10, in

**Comment by snvkgram** [comment]
I checked my egg file now. It is ibm_db_sa-0.33-py3.6.egg. It is working fine with py2.7 script. What troubled me whether it is egg file version or easy-install version or pip version..I don’t remember, sorry. But my current versions are: IBM dB version as above, Python 2.7 and pip 10.0.1 and setuptools 40.0.0 (Python 3.6). Pls don’t ask me why I have 3.6 also here!
