### ISSUE TITLE
Installation behind company firewall fails on downloading ntx64_odbc_cli.zip

### ISSUE THREAD

**Issue by Khris777** [ibmdb/python-ibmdb#304]
I'm sitting behind a company firewall and I'm trying to install `ibm_db` with pip:

    pip install ibm_db==2.0.8a --proxy=http://proxy.*******.net:****

The install fails at `Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip` with a `ConnectionResetError: [WinError 10054]` telling me that the connection was closed by the remote host.

I entered the URL into my browser and was able to download the file manually without problems. Then followed I the instructions on https://www-01.ibm.com/support/docview.wss?uid=swg21418043 to install and register the driver properly which all worked fine as well.

But the installation over pip doesn't seem to check for that, it just tries to download the driver again and fails again.

Any help would be appreciated.

System: Windows 10, 64 bit.

Full error output:

```
C:\>pip install ibm_db==2.0.8a --proxy=http://proxy.*******.net:****
Collecting ibm_db==2.0.8a
  Using cached ibm_db-2.0.8a.tar.gz
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
    Traceback (most recent call last):
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 1026, in _send_output
        self.send(msg)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 964, in send
        self.connect()
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\http\client.py", line 1400, in connect
        server_hostname=server_hostname)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\ssl.py", line 407, in wrap_socket
        _context=self, _session=session)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\ssl.py", line 814, in __init__
        self.do_handshake()
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\ssl.py", line 1068, in do_handshake
        self._sslobj.do_handshake()
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\My.Name\AppData\Local\Temp\pip-build-xhcaelev\ibm-db\setup.py", line 167, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 526, in open
        response = self._open(req, data)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 544, in _open
        '_open', req)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 504, in _call_chain
        result = func(*args)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\urllib\request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\My.Name\AppData\Local\Temp\pip-build-xhcaelev\ibm-db\
```

**Comment by SabaKauser** [comment]
Hello,
Please set IBM_DB_HOME=<path to newly installed driver upto clidriver folder> and retry install again.

Thanks,
Saba.

**Comment by SabaKauser** [comment]
Hello,
Please set IBM_DB_HOME= <path to clidriver folder> 
and retry install again. 
e.g: set IBM_DB_HOME=C:\Users\user1\clidriver

**Comment by SabaKauser** [comment]
not sure why would git not allow me to enclose text between angle brackets .

**Comment by Khris777** [comment]
For some reason the command didn't work, so I added it with the advanced system settings and the installation succeeded.

Thanks for the help.

**Comment by SabaKauser** [comment]
Thank you!
