### ISSUE TITLE
Apache superset - Error retrive table information (SqlAlchemy)

### ISSUE THREAD

**Issue by mariomarf** [ibmdb/python-ibmdb#320]
Hello,
when i try to get table information i receive "Error occurred while fetching table metadata". In log:
"

2018-05-23 22:43:22,945:INFO:werkzeug:192.168.158.1 - - [23/May/2018 22:43:22] "GET /superset/table/2/ttis11_ms_od_gio/TISA%20%20%20%20/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 905, in wrapper
    value = f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/superset/views/core.py", line 2253, in table
    cols=columns, latest_partition=False),
  File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 722, in select_star
    indent=indent, latest_partition=latest_partition, cols=cols)
  File "/usr/lib/python2.7/site-packages/superset/db_engine_specs.py", line 256, in select_star
    sql = my_db.compile_sqla_query(qry)
  File "/usr/lib/python2.7/site-packages/superset/models/core.py", line 713, in compile_sqla_query
    compiled = qry.compile(eng, compile_kwargs={'literal_binds': True})
  File "<string>", line 1, in <lambda>

  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 453, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib/python2.7/site-packages/ibm_db_sa-0.3.2-py2.7.egg/ibm_db_sa/base.py", line 351, in visit_select
    sql_ori = compiler.SQLCompiler.visit_select(self, select, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 1791, in visit_select
    text += self.get_select_precolumns(select, **kwargs)
TypeError: get_select_precolumns() got an unexpected keyword argument 'literal_binds' 

 "

Thanks, best regards
Mario

**Comment by enriquemt** [comment]
It is happening the same to me using the last ibm_db_sa driver with superset.

**Comment by abhi7436** [comment]
Hi,
I am not able to see ibm_db_sa configured in your pip list and also share your stack trace as well to have a better look.

Thanks,
Abhinav

**Comment by enriquemt** [comment]
Dear Abhinav, I did not user pip to install it, I build it manually and then copy the ibm_db_sa folder in order to be used by superset, the test connection to the DB works fine and I am able to see tables and columns from it.

![image](https://user-images.githubusercontent.com/1184775/43132040-de41a162-8f3a-11e8-93f9-80a60d2a2fff.png)

**Comment by ajgil** [comment]
Hi there!
I had installed using this doc (ibm-website) [https://www.ibm.com/support/knowledgecenter/es/SSEPGG_9.5.0/com.ibm.db2.luw.apdv.python.doc/doc/t0054367.html]

Used Ubuntu and sles15 python2.7 and python3.6 and got same error on selects.

news?

**Comment by abhi7436** [comment]
Hi @enriquemt ,
From logs I can see control is not coming to ibm_db_sa code. if it comes then error log will contain something like below.
ile "/usr/lib/python2.7/site-packages/ibm_db_sa-0.3.2-py2.7.egg/ibm_db_sa/base.py", line 351, in visit_select
sql_ori = compiler.SQLCompiler.visit_select(self, select, **kwargs)

Please install ibm_db_sa using pip to the latest version (0.3.3)

@ajgil ,
can you please share your sample script, because I tried to execute sample program mentioned in your given link but not seeing the issue and share your pip list as well.

Thanks,
Abhinav

**Comment by ajgil** [comment]
@abhi7436, @enriquemt from sles15 and python3.6 add Stack trace. Ibm_db, ibm_dbi and ibm_db_sa drivers are ok and on SQLEditor map db, schema and tables. When starting select against tables that got error.
```sh
sudo pip install ibm_db
sudo pip install ibm_db_sa
```
Python2.7 Test conn
```python
Python 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> import ibm_db_dbi
>>> import sqlalchemy
>>> import ibm_db_sa
>>> from sqlalchemy import *
>>> db2 = sqlalchemy.create_engine('ibm_db_sa://XXX:XXX@XXXX.XXX.org:50001/XXX')
>>>
```

```sh
2018-07-26 09:10:33,639:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:10:44,298:INFO:werkzeug:10.168.24.69 - - [26/Jul/2018 09:10:44] "GET /superset/schemas/2/ HTTP/1.1" 200 -
2018-07-26 09:10:44,372:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:10:54,485:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:11:04,559:INFO:werkzeug:10.168.24.69 - - [26/Jul/2018 09:11:04] "GET /superset/schemas/2/ HTTP/1.1" 200 -
2018-07-26 09:11:14,674:INFO:werkzeug:10.168.24.69 - - [26/Jul/2018 09:11:14] "GET /superset/tables/2/AOSAIDW%20/undefined/ HTTP/1.1" 200 -
2018-07-26 09:11:18,015:DEBUG:root:[stats_logger] (incr) table
2018-07-26 09:11:18,020:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:11:23,048:DEBUG:root:[stats_logger] (incr) extra_table_metadata
2018-07-26 09:11:28,152:INFO:werkzeug:10.168.24.69 - - [26/Jul/2018 09:11:28] "GET /superset/extra_table_metadata/2/aosdt086deleg/AOSAIDW%20/ HTTP/1.1" 200 -
2018-07-26 09:11:58,842:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa:/xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:11:58,844:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://xxxxus1:XXXXXXXXXX@xxxdbint.xxx.net:50001/XXXXX
2018-07-26 09:11:59,084:INFO:werkzeug:10.168.24.69 - - [26/Jul/2018 09:11:59] "GET /superset/table/2/aosdt086deleg/AOSAIDW%20/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 26, in wraps
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/superset/models/core.py", line 903, in wrapper
    value = f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/superset/views/core.py", line 2259, in table
    cols=columns, latest_partition=False),
  File "/usr/lib/python3.6/site-packages/superset/models/core.py", line 727, in select_star
    indent=indent, latest_partition=latest_partition, cols=cols)
  File "/usr/lib/python3.6/site-packages/superset/db_engine_specs.py", line 310, in select_star
    sql = my_db.compile_sqla_query(qry)
  File "/usr/lib/python3.6/site-packages/superset/models/core.py", line 716, in compile_sqla_query
    compiled = qry.compile(eng, compile_kwargs={'literal_binds': True})
  File "<string>", line 1, in <lambda>

  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 453, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/usr/lib/python3.6/site-packages/ibm_db_sa/base.py", line 354, in visit_select
    sql_ori = compiler.SQLCompiler.visit_select(self, select, **kwargs)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1791, in visit_select
    text += self.get_select_precolumns(select, **kwargs)
TypeError: get_select_precolumns() got an unexpected keyword argument 'literal_binds'
```

**Comment by abhi7436** [comment]
Hi,
I have made some code changes but having difficulty testing it. 
I have pasted below the code changes can you please try it out. It should fix the issue.
in base.py file please replace `def get_select_precolumns(self, select):` and `def limit_clause(self, select):` with below lines.

`def get_select_precolumns(self, select, **kwargs):`
`def limit_clause(self, select, **kwargs):`

Let me know if you still face the same issue.

Thanks,
Abhinav

**Comment by ajgil** [comment]
Hi there,
@abhi7436 your fix found!

```python
2018-07-27 13:30:05,604:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://XXXXXXXXXX:XXXXXXXXXX@XXXXXXXXXX.XXXXXXXXXX.net:50001/XXXXXXXXXX
2018-07-27 13:30:05,624:INFO:root:SELECT "XXXXXXXXXX" AS "XXXXXXXXXX", sum(XXXXXXXXXX) AS "XXXXXXXXXX"
FROM (SELECT XXXXXXXXXX,
XXXXXXXXXX,     
FROM "XXXXXXXXXX".XXXXXXXXXX FETCH FIRST 100 ROWS ONLY) AS expr_qry
WHERE "XXXXXXXXXX" >= '1918-07-27-00.00.00' AND "XXXXXXXXXX" <= '2018-07-27-13.30.05' GROUP BY "XXXXXXXXXX" ORDER BY "XXXXXXXXXX" DESC FETCH FIRST 50000 ROWS ONLY
2018-07-27 13:30:05,664:INFO:root:Database.get_sqla_engine(). Masked URL: ibm_db_sa://XXXXXXXXXX:XXXXXXXXXX@XXXXXXXXXX.XXXXXXXXXX.net:50001/XXXXXXXXXX
```

**Comment by benjaminsingleton** [comment]
@SabaKauser @abhi7436, I had to make the same changes as @ajgil to get Apache Superset to show table names without getting the same error. Is this an issue that is considered resolved and closed or should someone create a pull request for the changes to `get_select_precolumns` and `limit_clause`?
