### ISSUE TITLE
error while installing ibm_db

### ISSUE THREAD

**Issue by coldy145** [ibmdb/python-ibmdb#322]
Collecting ibm_db
  Using cached https://files.pythonhosted.org/packages/f8/6f/5f8186cb31021409235a948be5e29d77761ef92747a101360003747c4105/ibm_db-2.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-HHcZmS/ibm-db/setup.py", line 170, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python2.7/urllib2.py", line 431, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
        '_open', req)
      File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno -5] No address associated with hostname>

**Comment by coldy145** [comment]
if anyone could help me in resolving this error

**Comment by SabaKauser** [comment]
Is this problem still reproducible?
It seems like your machine is unable to get ip address of where site is hosted. If I ping, I get this address
 170.225.15.112.
Was the site down when you tried installing? 

you can try adding the ip address to /etc/hosts file
e.g: 
 170.225.15.112 public.dhe.ibm.com

**Comment by SabaKauser** [comment]
another thing, use ibm_db==2.0.8a while installing, although this has nothing to do with the error you are facing, you might run into other known problem  https://github.com/ibmdb/python-ibmdb/issues/303 #303 

use : pip install ibm_db==2.0.8a
