### ISSUE TITLE
Unable to install ibm_db from public pypi.

### ISSUE THREAD

**Issue by Maksymilian-Erazmus1** [ibmdb/python-ibmdb#328]
Hi,

When I try to install ibm_db using pip:
```
pip install ibm_db
```
It fails with error:
```
Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/f8/6f/5f8186cb31021409235a948be5e29d77761ef92747a101360003747c4105/ibm_db-2.0.8.tar.gz (689kB)
    100% |████████████████████████████████| 696kB 5.6MB/s
Building wheels for collected packages: ibm-db
  Running setup.py bdist_wheel for ibm-db ... error
  Complete output from command /Users/merazmus/anaconda3/envs/py35env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/cw/_myb5m0n549715lhxz1sn1wc0000gn/T/pip-install-6dvc2hx5/ibm-db/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/cw/_myb5m0n549715lhxz1sn1wc0000gn/T/pip-wheel-bvv5bnls --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/cw/_myb5m0n549715lhxz1sn1wc0000gn/T/pip-install-6dvc2hx5/ibm-db/setup.py", line 17, in <module>
      os.rename('tests','test_2')
  OSError: [Errno 66] Directory not empty: 'tests' -> 'test_2'
```

python version: Python 3.5.4
pip version: pip 10.0.1

**Comment by SabaKauser** [comment]
install as below:
pip install ibm_db==2.0.8a
