### ISSUE TITLE
Datetime issue with Informix

### ISSUE THREAD

**Issue by RenaudDemarneffe** [ibmdb/python-ibmdb#337]
I'm getting an error when I use datetime with Informix database (12.1).
Informix only support datetime with 5 digits after the seconds (DATETIME YEAR TO FRACTION(5) format) but datetime object in python has 6 digits after the seconds.
The ibm_db package seems not to convert correctly the datetime object as input parameter for Informix.

See the attached file to reproduce the problem: [app.txt](https://github.com/ibmdb/python-ibmdb/files/2363685/app.txt).
The table is defined as follow:
```
/* Create sub-type timeserie for Alarm_Measure_Meter */
CREATE ROW TYPE Alarm_Measure_Meter (
    measureTS                 DATETIME YEAR TO FRACTION(5),
    realMeasureTS             DATETIME YEAR TO FRACTION(5),
    val                               FLOAT
);


/* Create timeserie table */
CREATE TABLE Alarm_Measure (
  as

set                       VARCHAR (32, 0) NOT NULL,
  component                   VARCHAR (32, 0) NOT NULL,
  type                        CHAR (1) NOT NULL,
  measure                     TIMESERIES(Alarm_Measure_Meter),
  PRIMARY KEY (asset, component, type)
) LOCK MODE ROW;
```

The output log is: 
[outputLogs.txt](https://github.com/ibmdb/python-ibmdb/files/2363688/outputLogs.txt)

The error traceback is:
```
Traceback (most recent call last):
  File "/home/vmuser/.local/lib/python3.6/site-packages/ibm_db_dbi.py", line 1258, in _execute_helper
    return_value = ibm_db.execute(self.stmt_handler, parameters)
Exception: Statement Execute Failed: [IBM][CLI Driver][IDS/UNIX64] Extra characters at the end of a datetime or interval. SQLCODE=-1264

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmuser/P4A/test-python/app.py", line 59, in <module>
    curs.execute(sql, paramList)
  File "/home/vmuser/.local/lib/python3.6/site-packages/ibm_db_dbi.py", line 1356, in execute
    self._execute_helper(parameters)
  File "/home/vmuser/.local/lib/python3.6/site-packages/ibm_db_dbi.py", line 1268, in _execute_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: Statement Execute Failed: [IBM][CLI Driver][IDS/UNIX64] Extra characters at the end of a datetime or interval. SQLCODE=-1264
```

Is there a setting to configure this conversion, or is it possible to fix the package code?

_Remark:  This code must be executed on multiple environments (CentOS 7, Win 7, Win 10 and IBM Cloud buildpack)._

**Comment by SabaKauser** [comment]
Hello Renaud,

I am connecting to Informix 11 and I get this error:
C:\Users\skauser\Desktop\rocketrack\python>python app.txt
Locale setting: en_US.cp1252
Connection created
Raw measurets: 2018-09-08 21:00:30
measurets.strftime('%Y-%m-%d %H:%M:%S.%f')[:-1]: 2018-09-08 21:00:30.00000
SQL: update Alarm_Measure set measure = PutElemNoDups(measure, row(?, ?, ?)::Alarm_Measure_Meter) where asset = ? and component = ? and type = ?;
Params: ['2018-09-08 21:00:30.00000', '2018-09-08 21:00:30.00000', 10, 'FL595', 'Alarm', 'M']
Traceback (most recent call last):
  File "C:\Users\skauser\.virtualenvs\rest-Be9_bo9v\lib\site-packages\ibm_db_dbi.py", line 1258, in _execute_helper
    return_value = ibm_db.execute(self.stmt_handler, parameters)
Exception: Binding Error: [IBM][CLI Driver][IDS/UNIX64] Routine (putelemnodups) can not be resolved.  SQLCODE=-674

Do I need to be on Informix 12? I do see putelemnodups supported with 11 though.

**Comment by RenaudDemarneffe** [comment]
Hello Saba,

I use Informix 12 but I think Informix 11 has also the functionality.

To enable it, you need to create a time serie database, enable the time series blade module and create a time serie table. Here are the creation scripts 
[CreateTimeserieDBandTable.txt](https://github.com/ibmdb/python-ibmdb/files/2366467/CreateTimeserieDBandTable.txt)

However, I think that a classic table with DATETIME YEAR TO FRACTION(5) should have the same problem.

**Comment by SabaKauser** [comment]
Hello Renaud,
I do not have administrative privileges to login to IDS. I have dropped email to an expert to help setup the module/s.
I tried a column with DATETIME YEAR TO FRACTION(5) from Windows client , inserting same values as yours and I could see them getting inserted successfully.
Attaching the same for your reference.

Could you please collect traces for your problem:
to collect traces:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files.

[app2.txt](https://github.com/ibmdb/python-ibmdb/files/2369909/app2.txt)
output:
Locale setting: en_US.cp1252
Connection created
Raw measurets: 2018-09-11 21:00:30
measurets.strftime('%Y-%m-%d %H:%M:%S.%f')[:-1]: 2018-09-11 21:00:30.00000
SQL: update ts set measureTS = ? where id=?;
Params: ['2018-09-11 21:00:30.00000', 1]
Execution done: 1
SQL: update ts set measureTS = ? where id=?;
Params: [datetime.datetime(2018, 9, 11, 22, 0, 30), 2]
Execution done: 1
first result set
2018-09-11 21:00:30
1
2018-09-11 22:00:30
2

**Comment by RenaudDemarneffe** [comment]
Hello Saba,

Here are the trace files of the driver.
[trc.cli.txt](https://github.com/ibmdb/python-ibmdb/files/2371675/trc.cli.txt)
[trc.flw.txt](https://github.com/ibmdb/python-ibmdb/files/2371676/trc.flw.txt)
[trc.fmt.txt](https://github.com/ibmdb/python-ibmdb/files/2371677/trc.fmt.txt)
[trc.fmtc.txt](https://github.com/ibmdb/python-ibmdb/files/2371678/trc.fmtc.txt)

**Comment by SabaKauser** [comment]
Thanks for the traces Renaud.

From the traces, I see that the SQL_TYPE returned by server for update query is SQL_VARCHAR for timeseries column, probably due to row type. 
For both success and failure case, client is sending following:
         Var[00] Type: 0X3F Len: 0X7FFF
         Var[01] Type: 0X3F Len: 0X7FFF   --> 3F is varchar, 32k length.

The difference is the value:
success case: 2018-09-08 21:00:30.00000
failing case :  2018-09-08 21:00:30.000000 
If you pass 6 fraction length in success case, it would fail with same error.

If update query is modified to return timestamp type instead of row, your test case will pass, because server is honoring total length of 26 bytes.
Success case in my test:
         N-GDA Len: 0C Type: 76 ID: D0
            Var[00] Type: 0X03 Len: 0X0004
            Var[01] Type: 0X25 Len: 0X001A
            Var[02] Type: 0X25 Len: 0X001A
        Footer: Length: 6
        DATA:                              (ASCII)          (EBCDIC)
        0671E4D00001                       .q....           ..U}..
      NM: FDODTA - FD:OCA Data
        LL: 64    CP: 147A
        DATA:                              (ASCII)          (EBCDIC)
        00000A0000000032 3031382D30332D32  .......2018-03-2 ................
        302D31322E30302E 30302E3030303030  0-12.00.00.00000 ................
        3000323031382D30 332D32302D31322E  0.2018-03-20-12. ................
        30302E30302E3030 30303030          00.00.000000     ............

**Comment by RenaudDemarneffe** [comment]
Hello Saba,

Thanks for your reply.
Could you please explain me how I must modify the update query to return timestamp type instead of row?

**Comment by SabaKauser** [comment]
Try this for failing case:
update Alarm_Measure set measure = PutElemNoDups(measure, row(?::DATETIME YEAR TO FRACTION(5) , ?::DATETIME YEAR TO FRACTION(5), ?)::Alarm_Measure_Meter) where asset = ? and component = ? and type = ?
