### ISSUE TITLE
HTTP 500 ODBC CLI won't download

### ISSUE THREAD

**Issue by mstdokumaci** [ibmdb/python-ibmdb#350]
You refer to a download URL here: https://github.com/ibmdb/python-ibmdb/blob/c6fe669b16185724c2d2c223abf9ca75fd32cb58/IBM_DB/ibm_db/setup.py#L161

This URL returns a 500 error on setup.

Example error is for file: https://files.pythonhosted.org/packages/3f/61/389c6decacfed61c2724005b8c2be61f2c699f731b53af13517e5a0e6e98/ibm_db-2.0.9.tar.gz

**Comment by SabaKauser** [comment]
Hello Mustafa,
Could you please provide the full output of the setup. I would need to see which flavor is getting picked. There were changes that were made recently to IBM repository from where drivers are picked for auto-install and I need to know more details to understand the problem. Kindly share the full output of your setup command.

**Comment by mstdokumaci** [comment]
```
Installing dependencies from Pipfile.lock (a234ab)…
An error occurred while installing ibm-db==2.0.9 --hash=sha256:72a5b1911125311bfa53dab40cf6684965abf4a548181f4af53dbe7d527f68c6! Will try again.
Installing initially failed dependencies…
Collecting ibm-db==2.0.9 
  Using cached https://files.pythonhosted.org/packages/3f/61/389c6decacfed61c2724005b8c2be61f2c699f731b53af13517e5a0e6e98/ibm_db-2.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zeog9m65/ibm-db/setup.py", line 164, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by csantanapr** [comment]
This affecting IBM Cloud Functions runtime pipeline.
The url to download the driver `linuxx64_odbc_cli.tar.gz` is down or error.

I get same error under python 3 and using `2.0.9`

Please fix ASAP, as this is a blocking item for a fix we need to get thru our pipeline today for our python runtime.

```
Downloading https://files.pythonhosted.org/packages/3f/61/389c6decacfed61c2724005b8c2be61f2c699f731b53af13517e5a0e6e98/ibm_db-2.0.9.tar.gz (782kB)
    Complete output from command python setup.py egg_info:
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4rqrzt32/ibm-db/setup.py", line 164, in <module>
        file_stream = BytesIO(request.urlopen(url).read())
      File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by SabaKauser** [comment]
The site https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli seems to be down.
Meanwhile, you can set IBM_DB_HOME to an existing installation of cli driver on your machine continue the setup.
Details can be found in README -> https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/README.md
under IBM_DB_HOME heading.

**Comment by klada** [comment]
Please move these files to a more reliable server. IBM's servers don't seem to be a good choice.

**Comment by rdd** [comment]
Seconded.
Could someone please point me to an alternative URL for the odbc cli tarball for Linux 64bit?
Thanks.

**Comment by harshit-sh** [comment]
Running into the 500 internal server error during `ibm_db` installation. Can someone please take a look? cc @amukherjee28 @bimalkjha 

Stacktrace:
`
Collecting ibm_db==3.0.3
10:44:16    Downloading ibm_db-3.0.3.tar.gz (794 kB)
10:44:16    Preparing metadata (setup.py): started
10:44:16    Preparing metadata (setup.py): finished with status 'error'
10:44:16    ERROR: Command errored out with exit status 1:
10:44:16     command: /usr/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uuj4cv7w/ibm-db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uuj4cv7w/ibm-db/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hauqvq3c
10:44:16         cwd: /tmp/pip-install-uuj4cv7w/ibm-db/
10:44:16    Complete output (19 lines):
10:44:16    Detected 64-bit Python
10:44:16    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
10:44:16    Traceback (most recent call last):
10:44:16      File "<string>", line 1, in <module>
10:44:16      File "/tmp/pip-install-uuj4cv7w/ibm-db/setup.py", line 240, in <module>
10:44:16        file_stream = BytesIO(request.urlopen(url, context=context).read())
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
10:44:16        return opener.open(url, data, timeout)
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 523, in open
10:44:16        response = meth(req, response)
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
10:44:16        response = self.parent.error(
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 561, in error
10:44:16        return self._call_chain(*args)
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
10:44:16        result = func(*args)
10:44:16      File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
10:44:16        raise HTTPError(req.full_url, code, msg, hdrs, fp)
10:44:16    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
`
