### ISSUE TITLE
ibm_db_dbi.Error: ibm_db_dbi::Error: SystemError('<built-in function fetch_tuple> returned a result with an error set',)

### ISSUE THREAD

**Issue by ramstein74** [ibmdb/python-ibmdb#355]
Hi, im from Portugal so we have special chars like you can see below...

when i have a query that gets a row with this text
"PORCELANA PARA MAÇARICO DE IGNIÇ."
 in a table column i get the error

4.4:zeta@~/pyWork/Tasks/allTasks> python3 test1.py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 38: invalid                 start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1472, in                 _fetch_helper
    row = ibm_db.fetch_tuple(self.stmt_handler)
SystemError: <built-in function fetch_tuple> returned a result with an error set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test1.py", line 15, in <module>
    for row in c1:
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1128, in                 __next__
    row = self.fetchone()
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1492, in                 fetchone
    row_list = self._fetch_helper(1)
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1476, in                 _fetch_helper
    raise self.messages[-1]
ibm_db_dbi.Error: ibm_db_dbi::Error: SystemError('<built-in function fetch_tuple                > returned a result with an error set',)
4.4:zeta@~/pyWork/Tasks/allTasks>

All other records are parsed correctly.

any help?
regards

my code 
import ibm_db_dbi as db2 
conn = db2.connect() 
c1 = conn.cursor() sql="select * ..... " -> querying only the record that crashed the code... 
c1.execute(sql) 
for row in c1: 
    print(row)

if i change the string from "PORCELANA PARA MAÇARICO DE IGNIÇ." to "PORCELANA PARA MAÇARICO DE IGNI" removing the second Ç it works but having the second Ç triggers the error. Why?

**Comment by ramstein74** [comment]
opened another one more detailed
