### ISSUE TITLE
Dependent module libdb2.a(shr_64.o) could not be loaded. 

### ISSUE THREAD

**Issue by ramstein74** [ibmdb/python-ibmdb#358]
i deleted current ibm_db from my iseries 7.3
then  did 
pip3 install ibm_db
it installed ibm_db v.2.0.9

then my script has an erro running.

 >>python3 test1.py 
Traceback (most recent call last): File "test1.py", line 2, in import ibm_db_dbi as db2 File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 35, in import ibm_db ImportError: Could not load module /QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db.so. Dependent module libdb2.a(shr_64.o) could not be loaded. Could not load module libdb2.a(shr_64.o). System error: No such file or directory Could not load module /QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db.so. Dependent module /QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db.so could not be loaded. 4.4:zeta@~/pyWork/Tasks/allTasks>

any help?

**Comment by kadler** [comment]
The IBM i code has not been upstreamed yet, so installing via pip does not work correctly. You *must* use the version we ship via rpm/yum.

BTW, it hasn't been iSeries in over a decade.
