### ISSUE TITLE
error import ibm_db_dbi as module

### ISSUE THREAD

**Issue by rohitajgit** [ibmdb/python-ibmdb#496]
successfully installed ibm_db and ibm_db_sa on python 3.7.  Now when I try to run
e = create_engine("ibm_db_sa://user:pass@bbbb.com:60000/YYYY")

I get the following error.

Traceback (most recent call last):

  File "c:\python37\p37\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-22-7d4750087845>", line 3, in <module>
    e = create_engine("ibm_db_sa://user:pass@bbbb.com:60000/YYYY")

  File "c:\python37\p37\lib\site-packages\sqlalchemy\engine\__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)

  File "c:\python37\p37\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)

  File "c:\python37\p37\lib\site-packages\ibm_db_sa\ibm_db.py", line 104, in dbapi
    import ibm_db_dbi as module

  File "c:\python37\p37\lib\site-packages\ibm_db_dbi.py", line 846
    
    ^
SyntaxError: invalid syntax

It is unable to find ibm_db_dbi module.  Should I be used a lower version of Python?

**Comment by SabaKauser** [comment]
can you try replacing the c:\python37\p37\lib\site-packages\ibm_db_dbi.py with the one from our git source here -> https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py and see if the error goes away.
I think the problem could be happening to due exception clause syntax that should have replaced with python 3 syntax when the driver is installed via pip and it does not seem to happen somehow.

**Comment by rohitajgit** [comment]
Updating the file resolved the issue.  Thanks Saba.
