### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by dickreuter** [ibmdb/python-ibmdb#505]
When i try to pip install it I get

```
    During handling of the above exception, another exception occurred:
  Collecting ibm_db>=2.0.0
  Downloading http://pypi.site.com/packages/98/cb/f77d9bd5f64246074af364cc30e20e3044c533890f3b67d30e89615c2fc5/ibm_db-3.0.1.tar.gz (642 kB)
     |████████████████████████████████| 642 kB 705 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /local/scratch/venv/nd1/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-60zm8kcj/ibm-db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-60zm8kcj/ibm-db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-60zm8kcj/ibm-db/pip-egg-info
         cwd: /tmp/pip-install-60zm8kcj/ibm-db/
    Complete output (44 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/local/scratch//python-base/lib/python3.7/http/client.py", line 1244, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 1290, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 1239, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 966, in send
        self.connect()
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 1406, in connect
        super().connect()
      File "/local/scratch/python-base/lib/python3.7/http/client.py", line 938, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "/local/scratch/python-base/lib/python3.7/socket.py", line 707, in create_connection
        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
      File "/local/scratch/python-base/lib/python3.7/socket.py", line 748, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
  
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-60zm8kcj/ibm-db/setup.py", line 185, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 543, in _open
        '_open', req)
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/local/scratch/python-base/lib/python3.7/urllib/request.py", line 1319, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SabaKauser** [comment]
The site https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli is up now and accessible. It is maintained by IBM and there were temporary outages seen earlier as well, but was told that these are inevitable. Sorry for the inconvenience. please retry install.

**Comment by freeldev** [comment]
I am having this same problem.  I visited the website manually and the file is there.
