### ISSUE TITLE
CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999 when preparing STP-Call z/OS

### ISSUE THREAD

**Issue by kokosnuss** [ibmdb/python-ibmdb#515]
Hey Guys, i hope you can help me.
I'm trying to call a STP in a Db2 z/OS database. I managed to call the stp successfully from java with the jdbc-driver. Now i'm struggling with the odbc driver:
```
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'T00', 'PROCEDURE_NAME': 'JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN', 'NUM_INPUT_PARAMS': 1, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN'}
Traceback (most recent call last):
  File "/home/mst/PycharmProjects/universalagent/opcgen50.py", line 48, in <module>
    ibm_db.bind_param(stmt, 1, json, ibm_db.SQL_PARAM_INPUT, ibm_db.SQL_VARCHAR)
Exception: Describe Param Failed: [IBM][CLI Driver] CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999
```

My source code:
```
conn=ibm_db.connect("DATABASE=***;HOSTNAME=***;PORT=***;PROTOCOL=TCPIP;UID=***;PWD=***",'', ibm_db.QUOTED_LITERAL_REPLACEMENT_OFF)
json = '{"TABLEOWNER":"TWSTST", "SUBSYS":"OPT","APPLICATIONS": { "UT00JAA#UC4TEST" : { "VARNAMEA":"VALUEA" } } }'
resultSet = ibm_db.procedures(conn, "DB2U", "T00", '%IWS_OCCURRENCE%')
row = ibm_db.fetch_assoc(resultSet)
while row:
    print(row)
    row = ibm_db.fetch_assoc(resultSet)
rc = None
stmt = ibm_db.prepare(conn, "CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN(?,?)")
ibm_db.bind_param(stmt, 1, json, ibm_db.SQL_PARAM_INPUT, ibm_db.SQL_CLOB)
ibm_db.bind_param(stmt, 2, rc , ibm_db.SQL_PARAM_OUTPUT, ibm_db.SQL_SMALLINT)
```
The STP on z/OS has following parameters:
```
1 INPUT MCP CLOB 
2 OUTPUT RC SMALLINT
```
Driver-Level
```
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "DB2 v11.1.4.5", "special_39510", 
"DYN1911120100AMD64_39510", and Fix Pack "5".
```
STP-DDL
```
--#SET TERMINATOR `                                                 
  SET CURRENT SQLID=hidden`                                      
  CREATE PROCEDURE T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN   
     (IN MCP CLOB(1 M) FOR SBCS DATA CCSID EBCDIC ,                 
      OUT RETURN_CODE SMALLINT )                                    
    EXTERNAL NAME 'MODNMAE'                                          
    LANGUAGE COBOL  PARAMETER CCSID EBCDIC  PARAMETER STYLE GENERAL 
    NOT DETERMINISTIC  FENCED  CALLED ON NULL INPUT  NO SQL         
    NO PACKAGE PATH  NO DBINFO  COLLID C01  WLM ENVIRONMENT 'WLMENV'
    ASUTIME LIMIT 300000  STAY RESIDENT YES  PROGRAM TYPE MAIN      
    SECURITY USER  INHERIT SPECIAL REGISTERS  CONTINUE AFTER FAILURE
    RUN OPTIONS 'MSGFILE(,,,,ENQ)'  COMMIT ON RETURN NO `           
--#SET TERMINATOR ;                                                 
  COMMIT;                                                           
```
I hope you can help me, 
Regards!

**Comment by imavo** [comment]
Please try using ibm_db.callproc() for invoking stored procedures.

Example:

```
json='a json string'
rc=0
params = (json, rc)
stmt, json, rc = ibm_db.callproc(conn, "T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN", params)
...now process result-set (if one exists)
...and check the value of the output parameter in your rc variable

```

**Comment by kokosnuss** [comment]
I tried that but unfortunately same error:
```
Traceback (most recent call last):
  File "opcgen50.py", line 45, in <module>
    stmt, json, rc = ibm_db.callproc(conn, stp, params)
Exception: Describe Param Failed: [IBM][CLI Driver] CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999
```
Source Code:
```
params = (json, rc)
stmt, json, rc = ibm_db.callproc(conn, stp, params)
```

**Comment by imavo** [comment]
Is the Db2-for-Z stored-procedure written in SQL PL ?  . Can you also mention the exact version of your Db2-for-Z subsystem, whether NFM , and the Version/Release/Modification details.

**Comment by kokosnuss** [comment]
The Db2-for-Z stored-procedure calls an external program which is written in Cobol.
The Db2-for-Z subsystem is:
DB2 Rel   : 1215
DB2 F.Lvl : 501

**Comment by imavo** [comment]
Is the stored-procedure itself written in SQL PL ? (regardless of whether it calls a Cobol program) ?  Does it appear in SYSIBM.ROUTINES and SYSIBM.SYSPARMS?

**Comment by kokosnuss** [comment]
Yes, its written in SQL PL. And also yes, it appers in both SYSIBM tables.

**Comment by imavo** [comment]
And the schema and qualifier in those tables match your `callproc` ?

**Comment by kokosnuss** [comment]
Yes. As i mentioned above. I'm able to call the STP with the two provided params via jdbc and java successfully
Code:
```
Class.forName("com.ibm.db2.jcc.DB2Driver");
con = DriverManager.getConnection (url, user, password);
cstmt = con.prepareCall("CALL T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN(?,?)"); 
json = new String(Files.readAllBytes(Paths.get("data/input.json")));
cstmt.setString (1, json);
cstmt.registerOutParameter(2, Types.INTEGER);  
cstmt.executeUpdate();                
rc = cstmt.getInt(2); 
```

**Comment by imavo** [comment]
As a test, are you able to call the same stored procedure from a plain SQL-script on your workstation using the same Db2-driver, i.e. from the command line either with the `db2` clp, or via the `db2cli` tool? (The idea is to eliminate python temporarily just for testing).

**Comment by kokosnuss** [comment]
Yes, that works like a charm:
```
CALL T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN( 'a json string', 0)
```

**Comment by imavo** [comment]
A CLI trace is next step, with the db2trc command. See other posts on here for detailed instructions, which are also in the Db2 Knowledge center online.  When I try with Db2-LUW (i.e. Db2 server running on Linux) the python script successfully runs the stored procedure. So something different happens for Db2-for-Z/OS.

**Comment by kokosnuss** [comment]
I did some traces. My guess is, that it's failing when calling SYSIBM.SYSPROCEDURECOLS. 
As you can see in the snippets, via python, the is a sp called named SYSIBM.SYSPROCEDURECOLS. This is not the case when working directly with the db2cli.
PYTHON  ibm_db.callpro:
```
8010    SQLPrepareW( hStmt=1:1, pszSqlStr="CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN(  ?, ? )", cbSqlStr=59 )
( StmtOut="CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN(  ?, ? )" )

SQLPrepareW( )
8182    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

8183    SQLDescribeParam( hStmt=1:1, usPar=1, psSQLType=&00007ffdc5b71c46, puiParamDef=&00007ffdc5b71c4c, psScale=&00007ffdc5b71c48, psNullable=&00007ffdc5b71c4a )
( StmtOut="CALL SYSIBM.SQLPROCEDURECOLS(?,?,?,?,?)" )
( Row=1, iPar=1, fCType=SQL_C_CHAR, rgbValue=<NULL pointer>, pcbValue=-1, piIndicatorPtr=-1 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="T00" - x'543030', pcbValue=3, piIndicatorPtr=3 )
( Row=1, iPar=3, fCType=SQL_C_CHAR, rgbValue="JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN" - x'4A424630305F5055545F4957535F4F43435552454E43455F494E544F5F43555252454E545F504C414E', pcbValue=41, piIndicatorPtr=41 )
( Row=1, iPar=4, fCType=SQL_C_CHAR, rgbValue=<NULL pointer>, pcbValue=-1, piIndicatorPtr=-1 )
( Row=1, iPar=5, fCType=SQL_C_CHAR, rgbValue="DATATYPE='ODBC';UNDERSCORE=0;GRAPHIC=1;REPORTUDTS=0;TYPEMAPPINGS=UDT:LUWUDT,ROWID:VARBINARY,GRAPHIC:WCHAR,VARGRAPHIC:WVARCHAR,LONGVARGRAPHIC:WLONGVARCHAR;SUPPORTEDNEWTYPES=XML,DECFLOAT,BINARY,VARBINARY;REPORTARRAYELEMENT=1;" - x'44415441545950453D274F444243273B554E44455253434F52453D303B475241504849433D313B5245504F5254554454533D303B545950454D415050494E47533D5544543A4C55575544542C524F5749443A56415242494E4152592C475241504849433A57434841522C564152475241504849433A57564152434841522C4C4F4E47564152475241504849433A574C4F4E47564152434841523B535550504F525445444E455754595045533D584D4C2C444543464C4F41542C42494E4152592C56415242494E4152593B5245504F52544152524159454C454D454E543D313B', pcbValue=223, piIndicatorPtr=223 )
( return=0 )
( Requested Cursor Attributes=x'00000000' )
( Reply Cursor Attributes=x'0A000808' )
( Actual Cursor Attributes=x'0A000808' )

SQLDescribeParam( )
9334    <--- SQL_ERROR   Time elapsed - +0,000000E+000 seconds
```
PYTHON ibm_db.exec_immediate
```
8010    SQLExecDirectW( hStmt=1:1, pszSqlStr="CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN('json', 'out')", cbSqlStr=-3 )
( StmtOut="CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN('json','out')" )
( StmtOut="CALL T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN('json','out')" )
( Row=1, iPar=1, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=4, piIndicatorPtr=0 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=3, piIndicatorPtr=0 )
( StmtOut="CALL SYSIBM.SQLPROCEDURECOLS(?,?,?,?,?)" )
( Row=1, iPar=1, fCType=SQL_C_CHAR, rgbValue=<NULL pointer>, pcbValue=-1, piIndicatorPtr=-1 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="T00" - x'543030', pcbValue=3, piIndicatorPtr=3 )
( Row=1, iPar=3, fCType=SQL_C_CHAR, rgbValue="JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN" - x'4A424630305F5055545F4957535F4F43435552454E43455F494E544F5F43555252454E545F504C414E', pcbValue=41, piIndicatorPtr=41 )
( Row=1, iPar=4, fCType=SQL_C_CHAR, rgbValue=<NULL pointer>, pcbValue=-1, piIndicatorPtr=-1 )
( Row=1, iPar=5, fCType=SQL_C_CHAR, rgbValue="DATATYPE='ODBC';UNDERSCORE=0;GRAPHIC=1;REPORTUDTS=0;TYPEMAPPINGS=UDT:LUWUDT,ROWID:VARBINARY,GRAPHIC:WCHAR,VARGRAPHIC:WVARCHAR,LONGVARGRAPHIC:WLONGVARCHAR;SUPPORTEDNEWTYPES=XML,DECFLOAT,BINARY,VARBINARY;REPORTARRAYELEMENT=1;" - x'44415441545950453D274F444243273B554E44455253434F52453D303B475241504849433D313B5245504F5254554454533D303B545950454D415050494E47533D5544543A4C55575544542C524F5749443A56415242494E4152592C475241504849433A57434841522C564152475241504849433A57564152434841522C4C4F4E47564152475241504849433A574C4F4E47564152434841523B535550504F525445444E455754595045533D584D4C2C444543464C4F41542C42494E4152592C56415242494E4152593B5245504F52544152524159454C454D454E543D313B', pcbValue=223, piIndicatorPtr=223 )
( return=0 )
( Requested Cursor Attributes=x'00000000' )
( Reply Cursor Attributes=x'0A000808' )
( Actual Cursor Attributes=x'0A000808' )
( Retrying Call Statically since original call got SQLCODE==-440 )
( Row=1, iPar=1, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=4, piIndicatorPtr=0 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=3, piIndicatorPtr=0 )
( Retrying call got SQLCODE==-440 )
( Unretrieved error message="[IBM][CLI Driver][DB2] SQL0440N  No authorized routine named "T00.JBF00_PUT_IWS_OCCURENCE_INTO_CURRENT_PLAN" of type "" having compatible arguments was found.  SQLSTATE=42884
" )
( ROLLBACK REQUESTED=1 )
( ROLLBACK REPLY RECEIEVED=1 )
```
db2cli directly
```
SQLAllocStmt( phStmt=1:1 )
9635    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

9696    SQLPrepare( hStmt=1:1 )
( pszSqlStr="CALL T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN( 'json', 0)", cbSqlStr=-3 )
( StmtOut="CALL T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN('json',0)" )
( StmtOut="CALL T00.JBF00_PUT_IWS_OCCURRENCE_INTO_CURRENT_PLAN('json',0)" )

SQLPrepare( )
9943    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

9944    SQLGetStmtAttr( hStmt=1:1, fOption=Unknown value 65494, pvParam=&00007fff79dcc038, cbParamMax=0, pcbParam=<NULL pointer> )

SQLGetStmtAttr( pvParam=24 )
9960    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

9961    SQLNumParams( hStmt=1:1, pcPar=&00007fff79dcc03c )

SQLNumParams( pcPar=0 )
9975    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

9976    SQLExecute( hStmt=1:1 )
( Row=1, iPar=1, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=134, piIndicatorPtr=0 )
( Row=1, iPar=2, fCType=SQL_C_CHAR, rgbValue="" - x'', pcbValue=1, piIndicatorPtr=0 )
( return=0 )

SQLExecute( )
10317    <--- SQL_SUCCESS   Time elapsed - +0,000000E+000 seconds

```

**Comment by imavo** [comment]
your CLI trace shows literals in the call statement for the db2cli case. Are you able to use parameter-markers instead? (you can do this with the `db2` clp if your Db2-client has that command, and use a variable to assign a value for the clob param ).

Apart from that, Looks like the Db2 driver is choosing to call sysibm.sqlprocedurecols
when the ibm_db module invokes SQLDescribeParam() . 

Maybe because the driver thinks there is some mismatch in data types.

This is also suggested by the -440 in the exec_immediate() case trace.

Please can you edit your question to show the complete unmodified `create procedure` DDL of the sproc  (without the body of the sproc).

**Comment by kokosnuss** [comment]
unfortunately, i'm not able to user db2 clp here, only clpplus and this is using jdbc driver.
I'll add the ddl

**Comment by kokosnuss** [comment]
I got it. I had a typo in the stp name. OCURENCE instead of OCURRENCE!
