### ISSUE TITLE
Python3.7 DB2 - Symbol not found

### ISSUE THREAD

**Issue by klaugsand** [ibmdb/python-ibmdb#540]
After updating to Mac Catalina (version 10.15.6), I had to re-install Python and all dependent modules. My problem now is that when adding the module ibm_db, I get the following error message when trying to run my program:

`ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 2): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib`

I am using PyCharm 2018.3.7 (CE).

Anyone that has seen this, and have a fix for this?

**Comment by imavo** [comment]
Did you re-install gcc after updating the macos, and before you installed ibm_db module?

**Comment by klaugsand** [comment]
I did not install or upgrade gcc after updating macos. I have now uninstalled ibm-db, installed gcc (using brew) and re-installed ibm-db. Unfortunately, I get the same error when trying to run my Python program.

**Comment by rredburn** [comment]
seeing similar with python 3.8.  Users on 10.15.5 seem to be ok so maybe 10.15.6 changed libraries and IBM needs to compile a new driver package (libdb2.dylib)

**Comment by baklarz** [comment]
Same issues on 10.14.6 running with 3.6.8 or 3.7+. Have run this a variety of ways including in a Virtual environment. All fail with the same errors as reported above.

**Comment by Amal-David** [comment]
I've been facing the same issue as well when setting it up with Mac version 10.15.4 and python version 3.7

**Comment by kotofos** [comment]
Same issue on 10.13.6 and python 3.8 from brew. ibm_db-3.0.2.

```
>   import ibm_db
E   ImportError: dlopen(...venv/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 2): Symbol not found: ___cxa_throw_bad_array_new_length
E     Referenced from: ...venv/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib (which was built for Mac OS X 10.15)
E     Expected in: /usr/lib/libstdc++.6.0.9.dylib
E    in ...venv/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib

```

**Comment by SabaKauser** [comment]
Hello,
The problem is happening because of the v11.5 clidriver image that is uploaded here->
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

I have informed the site owner of the problem and they are working on solution.

**Comment by klaugsand** [comment]
Great. Thank you!

**Comment by bimalkjha** [comment]
@klaugsand @rredburn @imavo @kotofos @Amal-David @baklarz 
I am able to reproduce the problem on Mac High Sierra (v10.13.6).
```
$ python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ibm_db.so, 2): 
      Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Users/bjha/nodework/clidriver/lib/libdb2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libstdc++.6.0.9.dylib
 in /Users/bjha/nodework/clidriver/lib/libdb2.dylib
>>> quit()
$ objdump -t /usr/lib/libstdc++.6.0.9.dylib | grep ___cxa_throw_bad_array_new_length
$
$ otool -L /Users/bjha/nodework/clidriver/lib/libdb2.dylib
/Users/bjha/nodework/clidriver/lib/libdb2.dylib:
        libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
            (compatibility version 150.0.0, current version 1675.129.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current 
                  version 275.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
        /usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
Here we can see libdb2.dylib is looking for gcc version 8. So, I intalled latest version on gcc using `brew install gcc` command. It installed gcc10 under  /usr/local/Cellar/gcc/10.2.0 directory.
So, I set the environment variable to pickup this version of gcc and issue no longer exist! The existing version of /usr/lib/libstdc++.6.dylib is causing the problem.
```
$ export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/10.2.0/lib/gcc/10:$DYLD_LIBRARY_PATH
$ python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> print ibm_db
<module 'ibm_db' from '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ibm_db.so'>
>>> quit()

$ objdump -t /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/libstdc++.6.dylib | grep ___cxa_throw_bad_array_new_length
00000000000ee60b g     F __TEXT,__text_cold     ___cxa_throw_bad_array_new_length
$ /usr/local/Cellar/gcc/10.2.0/bin> gcc-10 --version
gcc-10 (Homebrew GCC 10.2.0) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ /usr/local/Cellar/gcc/10.2.0/bin>
```

Instead of updating environment variable DYLD_LIBRARY_PATH, you can rename existing /usr/lib/libstdc++.6.dylib and create a softlink of /usr/local/Cellar/gcc/10.2.0/lib/gcc/10/libstdc++.6.dylib as /usr/lib/libstdc++.6.dylib

We have updated clidriver used by ibm_db to version Db2 V11.5.4.0 which is built using gcc (GCC) 8. Previous clidriver was of version Db2 V11.1.4.5 and compiled using older SDK which is no longer supported on newer OS of Mac. Please upgrade your g++ compiler to latest version to use ibm_db using the default clidriver.

If you have issue in updating gcc compiler, then there is a work around to bypass this issue:

Download `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/macos64_odbc_cli.tar.gz` and untar it. You'll get clidriver directory. Then from terminal, run below commands:
```
export IBM_DB_HOME=<full_path_of_extracted_clidriver>
pip install ibm_db
```
Thanks.

**Comment by rredburn** [comment]
Thanks for the work around.  

In general this does not feel like a reasonable final solution for the general Python community that expects pip install to work on their Macs without jumping through hoops to install compilers they don't want (how will people even know they need to do that?).  Seems odd libdb2.dylib is being built against gcc for Macs when clang is the OS default and is what gets used to build the ibm_db shared library (at least on my box):  

```
building 'ibm_db' extension
creating build/temp.macosx-10.15-x86_64-3.8
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Iclidriver/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c ibm_db.c -o build/temp.macosx-10.15-x86_64-3.8/ibm_db.o
```  

Isn't the better answer to compile the Mac clidriver on a Mac using default system compilers/libs?  Or perhaps have ibm_db setup.py download  v11.5.4.0 or 11.1.4.5 (or etc.) based on detected system compatibility?

PS. suggesting modifying /usr/lib/libstdc++.6.dylib to point to a brew installed version seems dangerous -- who knows what other OS/application dependencies that may effect.  I would never tell users to hack /usr/lib  files/links manually.

**Comment by bimalkjha** [comment]
@rredburn You can install gcc using other ways too. Its version to be greater than 8. Using brew is not necessary. I had brew, so I used and shared the command.
Yes, we are working for better solution and will update here. Thanks.

**Comment by SabaKauser** [comment]
the better solution is to resolve the undefined symbol for mac builds of clidriver. Linux clidriver has the symbol defined. Python might just be one case, if other interfaces has this dependency, the clidriver on mac is problematic there as well as its the C++ lib.

**Comment by bimalkjha** [comment]
Documenting 2 quick solution for this issue here:

1.	Install and use gcc version >= 8
2.	export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/clidriver/lib

Thanks.

**Comment by killuazhu** [comment]
@bimalkjha @SabaKauser  do we have an ETA when a better fix would come? We use ibm-db as a dependency in our [detect-secrets](https://github.ibm.com/git-defenders/detect-secrets-stream/pull/455) tool, and it's affecting many of our macOs users now.

I tried the alternative IBM ODBC package trick from your suggestion [above](https://github.com/ibmdb/python-ibmdb/issues/540#issuecomment-673610706). It does work. While you guys are working on a better fix, as a tactical fix, can you please update [setup.py for ibmdb](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L204) to download db2 odbc driver package from that alternative location for macOs?

alternative location: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/macos64_odbc_cli.tar.gz

**Comment by killuazhu** [comment]
@bimalkjha @SabaKauser I added PR https://github.com/ibmdb/python-ibmdb/pull/543 for the suggestion above.

**Comment by SabaKauser** [comment]
> 
> 
> @bimalkjha @SabaKauser I added PR #543 to implement the suggestion above.

Hi @killuazhu ,
The setup.py changes will not be needed. Since the V11.5 driver on MAC is not working and the one in  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/macos64_odbc_cli.tar.gz is a v11.1 driver, I am in strong opinion of replacing V11.5 driver with V11.1 by default in the download repository itself. 

While having to pick the v11.1 from new location require a change to ibm_db and a new release, having to replace V11.5 image with V11.1 does not require any changes and both yields the same result.

**Comment by killuazhu** [comment]
@SabaKauser do we know when the v11.1 replacement will happen? I agree with you and also in favor of reverting from v11.5 back to v11.1 since it should prevent any new broken installation on macOS.

I hope this can happen very soon and I would be happy to drop my PR when it happens.

**Comment by bimalkjha** [comment]
@killuazhu v11.5 is also working fine by just setting below environment variable, no need to install any additional software.
```
export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/clidriver/lib
```
You can set it for ibm_db in `ibm_db_dbi.py` file to be effective automatically. I suggested Saba to set this env var in ibm-db code and have a new release. You may update your pull request to set this DYLD_LIBRARY_PATH in ibm_db_dbi.py instead of using older clidriver from linuxx64 dir. Thanks.

**Comment by SabaKauser** [comment]
@bimalkjha  setting in ibm_db_dbi.py won't have this in effect automatically. Its a Python DBI specification and gets imported only when use has imported ibm_db_dbi. This will not solve problem for all users.

**Comment by bimalkjha** [comment]
@SabaKauser Do you mean there is no way in ibm_db to set an environment variable for the process when package get loaded? I do not have much idea, but there should be some way as it exist for other language and package.
I had a quick look into setup.py and I think we need to run `install_name_tool` command for `libstdc++.so.6` too here: https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L54 . It will avoid need to set DYLD_LIBRARY_PATH. Please try and let us know that `install_name_tool` command solves the problem or not. Thanks.

**Comment by SabaKauser** [comment]
@killuazhu @klaugsand the clidriver is now updated with needed dependency and importing ibm_db should work without any problems.
Kindly verify and provide your feedback!

**Comment by bimalkjha** [comment]
@klaugsand @killuazhu @imavo @rredburn @baklarz @Amal-David @kotofos We have refreshed the clidriver with fix of this issue couple of minutes back. The issue should not be reproducible now.  No need to install new version of gcc and no need to set DYLD_LIBRARY_PATH. Please verify and let us know. Thanks.

**Comment by killuazhu** [comment]
@bimalkjha I can verify a fresh install of ibm-db pip package on macOs is working now! Thanks for pulling together the fix.

**Comment by oscarsan** [comment]
I'm having the same problem with catalina python3.9 and installing ibm_db 3.0.3 fresh. 
nothing has help.

**Comment by db2Dean** [comment]
I was having this problem too and was able to fix it as follows:
1.  Installed gcc 
       - this added the libstdc++ files/aliases, but did put them in the /usr/lib where my Mac Monterey was looking
 2. export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/11.2.0_1/lib/gcc/11:${DYLD_LIBRARY_PATH}
       - This finally fixed my issue.

**Comment by rodrigomartinezar** [comment]
I'm working on a Mac running on BigSur 11.6.2 struggling with the same problem for about a month and actually solved it by chance.

After creating a virtualenv for python 3.7.7 with pyenv, pip3 version was 19.2.3. Since I could not use that pip version due to packages conflicts, I always updated pip, but never got my project to work because of the error.

Today I created a new virtualenv but before upgrading pip, I installed ibm_db==3.0.4. Then, somehow, the problem disappeared. 

```
pyenv virtualenv 3.7.7 test
pyenv activate test
pip3 install ibm_db==3.0.4
```
After this, importing ibm_db on python works as expected. Finally, I just upgraded pip and installed the other packages and project worked just fine.

I don't know what happens on background but this solved my problem. Posting this in case anyone needs another workaround.

**Comment by bimalkjha** [comment]
This issue is fixed by latest clidriver which packages correct libstdc++.0.6.dylib library. Thanks.

**Comment by mjdavisibm** [comment]
Wondered where this got to with the latest releases.
Firstly I am getting the same problem as at the top of this issue, i.e. `Symbol not found: ___cxa_throw_bad_array_new_length`. 

My environment
Brand new Mac: Monterey 12.5.1
Installed : IBM Data Server Driver Package (DS Driver) V11.5.4 and then used fix central to get version 11.5.7 installed over it. I noticed 11.5.7 was released in Dec 2021, i.e. before @bimalkjha last comment on Jan 3rd above
Installed to default location : /Applications/dsdriver
Then I executed the following
```
$ export IBM_DB_HOME=/Applications/dsdriver
$ pip install ibm_db
$ export LD_LIBRARY_PATH=$IBM_DB_HOME/lib
$ pip install --upgrade --force-reinstall ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.3-cp39-cp39-macosx_12_0_x86_64.whl
Installing collected packages: ibm_db
  Attempting uninstall: ibm_db
    Found existing installation: ibm-db 3.1.3
    Uninstalling ibm-db-3.1.3:
      Successfully uninstalled ibm-db-3.1.3
Successfully installed ibm_db-3.1.3
$ python
Python 3.9.13 (main, Aug  9 2022, 06:41:34) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/matt/.pyenv/versions/venv_Storefront/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/Applications/dsdriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'
>>> 
```
Any thoughts? Do I need to wait for 11.5.8? and if so is that due out soon?

**Comment by jamsden** [comment]
11.5.8 didn't work for me. Same issue.

**Comment by bimalkjha** [comment]
@jamsden You need to install gcc8 on MacOS to fix this issue and add /usr/local/lib/gcc/8 to DYLD_LIBRARY_PATH environment variable. Thanks.

**Comment by metaces** [comment]
Thansk @bimalkjha. Work and save my day!
> 
>     1. Installed gcc
>        
>        * this added the libstdc++ files/aliases, but did put them in the /usr/lib where my Mac was looking
> 
>     2. export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/11.2.0_1/lib/gcc/11:${DYLD_LIBRARY_PATH}
>        
>        * This finally fixed my issue.

**Comment by safuente** [comment]
Thanks @metaces it works for me!
