### ISSUE TITLE
Error on import ibm_db: "Library not loaded: /usr/local/lib/gcc/8/libgcc_s.1.dylib"

### ISSUE THREAD

**Issue by justineyster** [ibmdb/python-ibmdb#548]
We have a Detect Secrets user who isn't able to use our tool because of the following import error when importing `ibm_db`:

Stack trace:

```
Wus-MacBook-Pro:~ wuwei$ pip show ibm-db
Name: ibm-db
Version: 3.0.2
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires:
Required-by: detect-secrets
Wus-MacBook-Pro:~ wuwei$ pip --version
pip 20.1 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
Wus-MacBook-Pro:~ wuwei$ python --version
Python 3.8.2
Wus-MacBook-Pro:~ wuwei$ detect-secrets --version
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/bin/detect-secrets", line 5, in
from detect_secrets.main import main
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/main.py", line 4, in
from detect_secrets.core import audit
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/core/audit.py", line 11, in
from ..plugins.common import initialize
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/plugins/common/initialize.py", line 5, in
from detect_secrets.core.usage import PluginOptions
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/core/usage.py", line 364, in
class PluginOptions:
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/core/usage.py", line 368, in PluginOptions
for name, plugin in import_plugins().items()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/plugins/common/util.py", line 37, in import_plugins
module = import_module('detect_secrets.plugins.{}'.format(module_name))
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/plugins/db2.py", line 17, in
raise ie
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/plugins/db2.py", line 7, in
import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 2): Library not loaded: /usr/local/lib/gcc/8/libgcc_s.1.dylib
Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib
Reason: image not found
```

We advised them to uninstall and reinstall, but this did not work. Any idea what they need to do to resolve the issue?

**Comment by dbpymon** [comment]
Had the same problem. Fastest solution was to de-install Python complete (not only ibm_db) and re-install at wanted level, followed by re-install needed packages including ibm_db. Took 3 minutes in total and solved the problem. Reason is described in 3.0.2 at https://github.com/ibmdb/python-ibmdb, pointing to the change of gcc version to be 8.4 for Db2 clidriver 11.5.4.

**Comment by amukherjee28** [comment]
Explanation provided. Closing the issue.
