### ISSUE TITLE
install of ibm_db

### ISSUE THREAD

**Issue by jstouthamhawk** [ibmdb/python-ibmdb#551]
i try this on ubuntu 20.02 on wsl windows 10. Python 3.8.2

root:~/jxports$ pip3 install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.0.2.tar.gz (718 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_2qy6cfc/ibm-db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_2qy6cfc/ibm-db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-_2qy6cfc/ibm-db/pip-egg-info
         cwd: /tmp/pip-install-_2qy6cfc/ibm-db/
    Complete output (44 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "/usr/lib/python3.8/urllib/request.py", line 1326, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/usr/lib/python3.8/http/client.py", line 1240, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
        self.send(msg)
      File "/usr/lib/python3.8/http/client.py", line 946, in send
        self.connect()
      File "/usr/lib/python3.8/http/client.py", line 1409, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
        return self.sslsocket_class._create(
      File "/usr/lib/python3.8/ssl.py", line 1040, in _create
        self.do_handshake()
      File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_2qy6cfc/ibm-db/setup.py", line 207, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.8/urllib/request.py", line 525, in open
        response = self._open(req, data)
      File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.8/urllib/request.py", line 1369, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/usr/lib/python3.8/urllib/request.py", line 1329, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by bimalkjha** [comment]
@jstouthamhawk When you reported this issue in Sep 2020, python 3.8.x was not supported by ibm_db, hence the error. Now, latest version of ibm_db support python version <= 3.9 as documented [here](https://github.com/ibmdb/python-ibmdb#-pre-requisites). So, this issue is fixed now. Let us know if you are still facing any problem while installing the latest version of ibm_db. Thanks.
