### ISSUE TITLE
Cannot install ibm_db package

### ISSUE THREAD

**Issue by sxnguyen** [ibmdb/python-ibmdb#562]
I keep getting internal 500 errors
```
bash-4.4# pip3 install ibm-db
WARNING: The directory '/app/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: ibm-db in /usr/local/lib64/python3.6/site-packages (3.0.1)
bash-4.4# pip3 install ibm-db==3.0.2
WARNING: The directory '/app/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ibm-db==3.0.2
  Downloading ibm_db-3.0.2.tar.gz (718 kB)
     |████████████████████████████████| 718 kB 665 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-84coeyo4/ibm-db/setup.py'"'"'; __file__='"'"'/tmp/pip-install-84coeyo4/ibm-db/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yw_z30_9
         cwd: /tmp/pip-install-84coeyo4/ibm-db/
    Complete output (19 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-84coeyo4/ibm-db/setup.py", line 207, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by amukherjee28** [comment]
Hi,

I believe this is an operational issue on the websites and should be resolved soon.
Please try again and check.

Using python 3.6.x
I just tried

pip3 install ibm_db
Collecting ibm_db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.2

**Comment by Wonong** [comment]
I have same problem too.

**Comment by sxnguyen** [comment]
Thank you.  It works but keeps failing intermittently which cause our Jenskin build to fail.
