### ISSUE TITLE
Failed to get current schema when using IBM Cloud IAM authentication

### ISSUE THREAD

**Issue by shawnzhu** [ibmdb/python-ibmdb#578]
## Problem

environment: Python 3.7, ibm_db 3.0.2

When following the official guide [Identity and access management (IAM) on IBM Cloud](https://www.ibm.com/support/knowledgecenter/en/SS6NHC/com.ibm.swg.im.dashdb.security.doc/doc/iam.html)
Given Db2 warehouse in cloud, 
And example file `test_sqlalchemy.py` like this:
```Python
from sqlalchemy import text
from sqlalchemy import create_engine

SQLALCHEMY_URL= f'db2+ibm_db://@{db_host}:50001/BLUDB;CURRENTSCHEMA=KZHU_TEST;PROTOCOL=TCPIP;SECURITY=SSL;Authentication=GSSplugin;AccessToken={JWT_TOKEN}'

sql = text('SELECT * FROM TEST_ACTOR')
engine = create_engine(os.environ['SQLALCHEMY_URL'])
result = engine.execute(sql)

names = [row[0] for row in result]

print(names)
```

It will throw this error when running above python code:

```
pipenv run python test_sqlalchemy.py 
Loading .env environment variables...
user:  
Traceback (most recent call last):
  File "test_sqlalchemy.py", line 12, in <module>
    result = engine.execute(sql)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2234, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    ).exec_once_unless_exception(self.connection, self)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 1397, in go
    return once_fn(*arg, **kw)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/ibm_db_sa/base.py", line 698, in initialize
    super(DB2Dialect, self).initialize(connection)
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 319, in initialize
    connection
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/ibm_db_sa/ibm_db.py", line 202, in _get_default_schema_name
    return self.normalize_name(connection.connection.get_current_schema())
  File "/root/.local/share/virtualenvs/butane-c47Aapyx/lib/python3.7/site-packages/ibm_db_dbi.py", line 812, in get_current_schema
    return self.current_schema
AttributeError: 'Connection' object has no attribute 'current_schema'
```

## Analysis

First of all, a similar DSN works when using JDBC interface, so the IAM authentication works as designed.

Notice that there's NO user id nor password since the credential will be passed via the access token which includes such info with signature. So the below line of code will cause the current_schema to be an empty string:

https://github.com/ibmdb/python-ibmdb/blob/778f63228517040ca5c3d4c3d77589116c635c9e/IBM_DB/ibm_db/ibm_db_dbi.py#L600

When retrieving current schema, it just ignored the current schema since it's an empty string:

https://github.com/ibmdb/python-ibmdb/blob/778f63228517040ca5c3d4c3d77589116c635c9e/IBM_DB/ibm_db/ibm_db_dbi.py#L801-L810

Then the above AttributeError is expected since there indeed is no attribute named `current_schema`.

## Suggested fix

It could introduce a new feature to allow overriding the current_schema via ODBC option `CURRENTSCHEMA`, so that if there's no userid, it still work if user provides this option.

**Comment by shawnzhu** [comment]
@SabaKauser May I ask for a review from you?

**Comment by SabaKauser** [comment]
@amukherjee28 can you please review the PR.
