### ISSUE TITLE
ibm_db won't install

### ISSUE THREAD

**Issue by jackmurak** [ibmdb/python-ibmdb#609]
Hi, I have been trouble shooting with all the previously reported issues and can't get it to work.  Can someone help with this error?  Thanks,

_Collecting ibm_db==3.0.3
  Using cached ibm_db-3.0.3.tar.gz (794 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jm273\pycharmprojects\pythonproject\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jm273\\AppData\\Local\\Temp\\pip-install-tqdx_dbc\\ibm-db_c4c4627cb9da4c06a626772f2ea15a55\\setup.py'"'"'; __file__='"'"'C:\\Users\\jm273\\AppData\\Local\\Temp\\pip-install-tqdx_dbc\\ibm-db_c4c4627cb9da4c06a626772f2ea15a55\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jm273\AppData\Local\Temp\pip-pip-egg-info-j62bu_xe'
         cwd: C:\Users\jm273\AppData\Local\Temp\pip-install-tqdx_dbc\ibm-db_c4c4627cb9da4c06a626772f2ea15a55\
    Complete output (44 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
    Traceback (most recent call last):
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 1350, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 1262, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 1308, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 1257, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 1028, in _send_output
        self.send(msg)
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 968, in send
        self.connect()
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 1424, in connect
        super().connect()
      File "C:\Users\jm273\Python\Python37\lib\http\client.py", line 940, in connect
        (self.host,self.port), self.timeout, self.source_address)
      File "C:\Users\jm273\Python\Python37\lib\socket.py", line 728, in create_connection
        raise err
      File "C:\Users\jm273\Python\Python37\lib\socket.py", line 716, in create_connection
        sock.connect(sa)
    TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jm273\AppData\Local\Temp\pip-install-tqdx_dbc\ibm-db_c4c4627cb9da4c06a626772f2ea15a55\setup.py", line 240, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 525, in open
        response = self._open(req, data)
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 543, in _open
        '_open', req)
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
        result = func(*args)
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 1393, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Users\jm273\Python\Python37\lib\urllib\request.py", line 1352, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5d/0d/684a44f2449b0b731932a11e98e48085be96af3f44c0b196d56a0ecfdd52/ibm_db-3.0.3.tar.gz#sha256=2b24ce0a28868e83ac812dde4ba734071964e863b60d56da0ec178c06443351c (from https://pypi.org/simple/ibm-db/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ibm_db==3.0.3
ERROR: No matching distribution found for ibm_db==3.0.3_

**Comment by amukherjee28** [comment]
Hi @jackmurak

Let me understand the problem a bit more.
You are using windows with python version 3.7.

On doing pip install you are getting the error WinError 10060.

Please have a look a following link https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060

This looks to be more a network/configuration issue rather than driver issue.

Thanks.

**Comment by jackmurak** [comment]
I got it...it was a matter of drivers....needed to declare a system variable.
