### ISSUE TITLE
ibm_db.procedures returns no results when using Python on z/OS, connecting to Db2 for z/OS

### ISSUE THREAD

**Issue by kenjaninja** [ibmdb/python-ibmdb#637]
When using Python on z/OS, connecting to Db2 for z/OS, the `ibm_db.procedures` method returns no results/False for a given schema, even though `ibm_db.procedure_columns` is able to retrieve columns for that same schema.

Example code:
```
db_connection = ibm_db.connect('', '', '')

schema_name = 'SYSPROC'
result_set = ibm_db.procedures(db_connection, None, schema_name, '')

  data_record = ibm_db.fetch_assoc(result_set)
  if data_record:
      print(f"At least one stored procedure found for schema {schema_name}")
      print(data_record, '\n')
  else:
      print(f"No stored procedures found for schema {schema_name}\n")

  procedure_name = 'ACCEL_ADD_ACCELERATOR'
  result_set = ibm_db.procedure_columns(db_connection, '', schema_name, procedure_name, None)
  data_record = ibm_db.fetch_assoc(result_set)

  if not data_record:
      print(f"Columns for procedure {schema_name}.{procedure_name} could not be retrieved")

  while data_record:
      print(f"Stored procedure {schema_name}.{procedure_name} details:")
      print("____________________________________________________________")
      print(f"Procedure schema                   : {data_record['PROCEDURE_SCHEM']}")
      print(f"Procedure name                     : {data_record['PROCEDURE_NAME']}")
      print(f"Parameter name                     : {data_record['COLUMN_NAME']}")
      data_record = ibm_db.fetch_assoc(result_set)
```

**Comment by kenjaninja** [comment]
Here is the trace file: [trace.txt](https://github.com/ibmdb/python-ibmdb/files/6672535/trace.txt)

**Comment by imavo** [comment]
please try with `result_set = ibm_db.procedures(db_connection,  schema_name, None, '')`  .
Run a query on sysibm.sysroutines for your procedure(s) to find the values in the SCHEMA and OWNER columns.

**Comment by kenjaninja** [comment]
Using `result_set = ibm_db.procedures(db_connection, schema_name, None, '')` results in this output:
```
Exception: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HYC00  ERRLOC=10:22:5 SQLCODE=-99999

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 47, in <module>
    result_set = ibm_db.procedures(db_connection, schema_name, None, '')
SystemError: <built-in function procedures> returned a result with an error set
```
Here is the trace file: [trace.txt](https://github.com/ibmdb/python-ibmdb/files/6688689/trace.txt)

---
`SYSIBM.SYSROUTINES` query:
```
db_connection = ibm_db.connect('', '', '')

stmt = ibm_db.exec_immediate(db_connection, "SELECT SCHEMA, OWNER, NAME FROM SYSIBM.SYSROUTINES WHERE SCHEMA = 'SYSPROC'")
if stmt:
    result = ibm_db.fetch_assoc(stmt)
    while result:
        print(result)
        result = ibm_db.fetch_assoc(stmt)
```
Output:
```
{'SCHEMA': 'SYSPROC', 'OWNER': 'DB2SYS', 'NAME': 'ACCEL_ADD_ACCELERATOR'}
{'SCHEMA': 'SYSPROC', 'OWNER': 'DB2SYS', 'NAME': 'ACCEL_ADD_ACCELERATOR2'}
{'SCHEMA': 'SYSPROC', 'OWNER': 'DB2SYS', 'NAME': 'ACCEL_ADD_TABLES'}
...
```

**Comment by imavo** [comment]
And what result with `result_set = ibm_db.procedures(db_connection, 'DB2SYS', 'SYSPROC', '%') ` ?

**Comment by kenjaninja** [comment]
Result:
```
Exception: {DB2 FOR OS/390}{ODBC DRIVER}  SQLSTATE=HYC00  ERRLOC=10:22:5 SQLCODE=-99999

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    result_set = ibm_db.procedures(db_connection, 'DB2SYS', 'SYSPROC', '%')
SystemError: <built-in function procedures> returned a result with an error set
```
Trace: [trace.txt](https://github.com/ibmdb/python-ibmdb/files/6689356/trace.txt)

**Comment by lyangus** [comment]
I think this is an application error:

In the application ibm_db.procedures(db_connection, None, schema_name, '')<--the last parameter is '' which is supposed to be procedure name.  
I checked the ODBC trace, the procedure name is passed as X'' empty string, return no result is expected.  
[020D05D3 0000000000000001] SQLProceduresW( hStmt=1, szProcCatalog=Null Pointer, cbProcCatalog=-3, szProcSchema="SYSPROC", cbProcSchema=-3, szProcName="", cbProcName=-3 )
[020D05D3 0000000000000001] ( iPar=1, fCType=SQL_C_CHAR, rgbValue=Null data, pcbValue=-1 )
[020D05D3 0000000000000001] ( iPar=2, fCType=SQL_C_CHAR, rgbValue=x'53595350524F43', pcbValue=7 )
[020D05D3 0000000000000001] ( iPar=3, fCType=SQL_C_CHAR, rgbValue=x'', pcbValue=0 )
[020D05D3 0000000000000001] ( iPar=4, fCType=SQL_C_CHAR, rgbValue=x'', pcbValue=0 )
[020D05D3 0000000000000001] SQLProceduresW( )

If the (db_connection, None, schema_name, '')->. (db_connection, None, schema_name, 'ACCEL_ADD_ACCELERATOR')
if you do have this proc existed, then the result should be returned.

**Comment by lyangus** [comment]
For the second ODBC trace, 
 result_set = ibm_db.procedures(db_connection, 'DB2SYS', 'SYSPROC', '%')  passed the second parameter 'DB2SYS' is wrong. Should Keep None as input.

**Comment by amukherjee28** [comment]
Hi,

I am able to run both the ibm_db.procedures get procedures name and ibm_db.procedure_column to fetch column details out of a procedure in ZOS.

Here is the sample code : 

```
import ibm_db

print("IBM DB VERSION : " + str(ibm_db.__version__))

print("=> Creating Connection")

conn = ibm_db.connect('','','')


schemaName = "SYSPROC"

print("=> DISPLAY PROCEDURES")
res = ibm_db.procedures(conn,None,schemaName,'DBG%')
row = ibm_db.fetch_assoc(res)
while row:
    print(row)
    row = ibm_db.fetch_assoc(res)

print("=> Procedure columns")

res1 = ibm_db.procedure_columns(conn,'','SYSPROC','DBG_PINGSESSIONMANAGER',None)
row = ibm_db.fetch_assoc(res1)

while row:
    print(row)
    print("Procedure {} is having one output parameter with name {}\n".format(row['PROCEDURE_NAME'], row['COLUMN_NAME']))
    row = ibm_db.fetch_assoc(res1)
```

OUTPUT

```
bash-4.3$ python procedure1.py
IBM DB VERSION : 3.0.4
=> Creating Connection
=> DISPLAY PROCEDURES
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_ENDSESSIONMANAGER', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_ENDSESSIONMANAGER'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_INITIALIZECLIENT', 'NUM_INPUT_PARAMS': 3, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_INITIALIZECLIENT'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_LOOKUPSESSIONMANAGER', 'NUM_INPUT_PARAMS': 0, 'NUM_OUTPUT_PARAMS': 2, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_LOOKUPSESSIONMANAGER'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_PINGSESSIONMANAGER', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_PINGSESSIONMANAGER'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_RECVCLIENTREPORTS', 'NUM_INPUT_PARAMS': 3, 'NUM_OUTPUT_PARAMS': 3, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_RECVCLIENTREPORTS'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_RUNSESSIONMANAGER', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_RUNSESSIONMANAGER'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_SENDCLIENTCOMMANDS', 'NUM_INPUT_PARAMS': 5, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_SENDCLIENTCOMMANDS'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_SENDCLIENTREQUESTS', 'NUM_INPUT_PARAMS': 3, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_SENDCLIENTREQUESTS'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_TERMINATECLIENT', 'NUM_INPUT_PARAMS': 3, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'DBG_TERMINATECLIENT'}
=> Procedure columns
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_PINGSESSIONMANAGER', 'COLUMN_NAME': 'HOST', 'COLUMN_TYPE': 1, 'DATA_TYPE': 12, 'TYPE_NAME': 'VARCHAR', 'COLUMN_SIZE': 128, 'BUFFER_LENGTH': 128, 'DECIMAL_DIGITS': None, 'NUM_PREC_RADIX': None, 'NULLABLE': 1, 'REMARKS': None, 'COLUMN_DEF': None, 'SQL_DATA_TYPE': 12, 'SQL_DATETIME_SUB': None, 'CHAR_OCTET_LENGTH': 128, 'ORDINAL_POSITION': 1, 'IS_NULLABLE': 'YES'}
Procedure DBG_PINGSESSIONMANAGER is having one output parameter with name HOST

{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_PINGSESSIONMANAGER', 'COLUMN_NAME': 'PORT', 'COLUMN_TYPE': 1, 'DATA_TYPE': 4, 'TYPE_NAME': 'INTEGER', 'COLUMN_SIZE': 10, 'BUFFER_LENGTH': 4, 'DECIMAL_DIGITS': 0, 'NUM_PREC_RADIX': 10, 'NULLABLE': 1, 'REMARKS': None, 'COLUMN_DEF': None, 'SQL_DATA_TYPE': 4, 'SQL_DATETIME_SUB': None, 'CHAR_OCTET_LENGTH': None, 'ORDINAL_POSITION': 2, 'IS_NULLABLE': 'YES'}
Procedure DBG_PINGSESSIONMANAGER is having one output parameter with name PORT

{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'DBG_PINGSESSIONMANAGER', 'COLUMN_NAME': 'XMLREPLY', 'COLUMN_TYPE': 4, 'DATA_TYPE': -98, 'TYPE_NAME': 'BLOB', 'COLUMN_SIZE': 32768, 'BUFFER_LENGTH': 32768, 'DECIMAL_DIGITS': None, 'NUM_PREC_RADIX': None, 'NULLABLE': 1, 'REMARKS': None, 'COLUMN_DEF': None, 'SQL_DATA_TYPE': -98, 'SQL_DATETIME_SUB': None, 'CHAR_OCTET_LENGTH': 32768, 'ORDINAL_POSITION': 3, 'IS_NULLABLE': 'YES'}
Procedure DBG_PINGSESSIONMANAGER is having one output parameter with name XMLREPLY

bash-4.3$
```

Can we have a look into the INI file used to run the program in order to check if something is going wrong.

Thanks

**Comment by kenjaninja** [comment]
Here is the INI file:
```
[COMMON]
APPLTRACE=1
APPLTRACEFILENAME=DD:APPLTRC
DIAGTRACE=1
DIAGTRACE_NO_WRAP=0
MVSDEFAULTSSID=DL7G
CONNECTTYPE=1
MULTICONTEXT=2
CURRENTAPPENSCH=ASCII
FLOAT=IEEE
[DL7G]
MVSATTACHTYPE=RRSAF
PLANNAME=DSNACLI
[DSNL7]
AUTOCOMMIT=1
CURSORHOLD=1
```

**Comment by amukherjee28** [comment]
I am able to run the program with exact same INI file.

There are few changes you need to consider changing in your application code.

1. After fetching the procedures list using the ```ibm_db.procedures``` call you need to change the subsequent if statement with a while loop so as to fetch all records one after the another till the end of the result set.
2. In the ```result_set = ibm_db.procedures(db_connection, None, schema_name, '')``` statement you can use % symbol at the end to fetch list of all procedures.

Complete code after the changes :

```
db_connection = ibm_db.connect('', '', '')

schema_name = "SYSPROC"
result_set = ibm_db.procedures(db_connection, None, schema_name, '%')

data_record = ibm_db.fetch_assoc(result_set)
while data_record:
    if data_record:
      print(f"At least one stored procedure found for schema {schema_name}")
      print(data_record, '\n')
      data_record = ibm_db.fetch_assoc(result_set)
    else:
      print(f"No stored procedures found for schema {schema_name}\n")

procedure_name = 'DBG_PINGSESSIONMANAGER'
result_set = ibm_db.procedure_columns(db_connection, '', schema_name, procedure_name, None)
data_record = ibm_db.fetch_assoc(result_set)

if not data_record:
  print(f"Columns for procedure {schema_name}.{procedure_name} could not be retrieved")

while data_record:
  print(f"Stored procedure {schema_name}.{procedure_name} details:")
  print("____________________________________________________________")
  print(f"Procedure schema                   : {data_record['PROCEDURE_SCHEM']}")
  print(f"Procedure name                     : {data_record['PROCEDURE_NAME']}")
  print(f"Parameter name                     : {data_record['COLUMN_NAME']}")
  data_record = ibm_db.fetch_assoc(result_set)
```

Extracted Output :

```
At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'WLM_REFRESH', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 2, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'WLM_REFRESH'}

At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'WLM_SET_CLIENT_INFO', 'NUM_INPUT_PARAMS': 4, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'WLM_SET_CLIENT_INFO'}

At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_ADDSCHEMADOC', 'NUM_INPUT_PARAMS': 5, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_ADDSCHEMADOC'}

At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_COMPLETE', 'NUM_INPUT_PARAMS': 4, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_COMPLETE'}

At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_REGISTER', 'NUM_INPUT_PARAMS': 4, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_REGISTER'}

At least one stored procedure found for schema SYSPROC
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_REMOVE', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_REMOVE'}

Stored procedure SYSPROC.DBG_PINGSESSIONMANAGER details:
____________________________________________________________
Procedure schema                   : SYSPROC
Procedure name                     : DBG_PINGSESSIONMANAGER
Parameter name                     : HOST
Stored procedure SYSPROC.DBG_PINGSESSIONMANAGER details:
____________________________________________________________
Procedure schema                   : SYSPROC
Procedure name                     : DBG_PINGSESSIONMANAGER
Parameter name                     : PORT
Stored procedure SYSPROC.DBG_PINGSESSIONMANAGER details:
____________________________________________________________
Procedure schema                   : SYSPROC
Procedure name                     : DBG_PINGSESSIONMANAGER
Parameter name                     : XMLREPLY
```

**Comment by kenjaninja** [comment]
I get the same output. With the added % symbol, this does work around the issue, but there exists a discrepancy between non-z/OS systems and z/OS when running `ibm_db.procedures` with a blank procedure name.

On Windows, running `ibm_db.procedures(conn, None, schemaName, '')` fetches all procedures for the given schema, while on z/OS, as we have seen, it fetches none. 

Windows (username & password omitted):
```
db_connection = ibm_db.connect('DRIVER={IBM DB2 ODBC DRIVER};ATTACH=FALSE;DATABASE=DSNL7;HOSTNAME=9.30.178.45;PORT=53900;PROTOCOL=TCPIP;UID=USERNAME;PWD=PASSWORD,'', '')

schema_name = "SYSPROC"
result_set = ibm_db.procedures(db_connection, None, schema_name, '')

print("Displaying procedures")
data_record = ibm_db.fetch_assoc(result_set)

if not data_record:
    print(f"No stored procedures found for schema {schema_name}\n")

while data_record:
    if data_record:
        print(data_record)
        data_record = ibm_db.fetch_assoc(result_set)
```
Output:
```
Displaying procedures
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'ACCEL_ADD_ACCELERATOR', 'NUM_INPUT_PARAMS': 5, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 1, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'ACCEL_ADD_ACCELERATOR'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'ACCEL_ADD_ACCELERATOR2', 'NUM_INPUT_PARAMS': 6, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 1, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'ACCEL_ADD_ACCELERATOR2'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'ACCEL_ADD_TABLES', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 1, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'ACCEL_ADD_TABLES'}
...
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_REGISTER', 'NUM_INPUT_PARAMS': 4, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_REGISTER'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'XSR_REMOVE', 'NUM_INPUT_PARAMS': 2, 'NUM_OUTPUT_PARAMS': 0, 'NUM_RESULT_SETS': 0, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'XSR_REMOVE'}
{'PROCEDURE_CAT': None, 'PROCEDURE_SCHEM': 'SYSPROC', 'PROCEDURE_NAME': 'ZPARMPROC', 'NUM_INPUT_PARAMS': 0, 'NUM_OUTPUT_PARAMS': 1, 'NUM_RESULT_SETS': 1, 'REMARKS': '', 'PROCEDURE_TYPE': 1, 'SPECIFIC_NAME': 'ZPARMPROC'}
```        

z/OS:
```
db_connection = ibm_db.connect('', '', '')

schema_name = "SYSPROC"
result_set = ibm_db.procedures(db_connection, None, schema_name, '')

print("Displaying procedures")
data_record = ibm_db.fetch_assoc(result_set)

if not data_record:
    print(f"No stored procedures found for schema {schema_name}\n")

while data_record:
    if data_record:
        print(data_record)
        data_record = ibm_db.fetch_assoc(result_set)
```
Output:
```
Displaying procedures
No stored procedures found for schema SYSPROC
```

I understand this is not too big of an issue, but I feel that resolving these inconsistencies will avoid possible confusion in the future for users.

**Comment by amukherjee28** [comment]
The interpretation of the syntax is dependent also on the underlying drivers that connections and fetch the data.
In case of non ZOS system its the clidriver that fetches the data from db2 servers and in case of ZOS system its the Z-odbc drivers that does the job.

So the interpretation of parameters are sometimes dependent on the underlying driver as well. Here the difference is really small and we have to adhere to the syntax.

Thanks.
