### ISSUE TITLE
Installation error when downloading ODBC drivers

### ISSUE THREAD

**Issue by luisdelatorre012** [ibmdb/python-ibmdb#667]
I'm getting an error when trying to `pip install --proxy <corporate proxy url> ibm_db` behind a corporate firewall, when setup.py tries to download `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip`. I've tried passing it as a trusted host to pip and get the same error:

```pip install --proxy <corporate proxy url> --trusted-host public.dhe.ibm.com ibm_db```

I can install other packages just fine. Totally stumped on what to do here. Is there a way I can download the odbc cli separately and have the install recognize it?

I'm running python 3.9.6 on Windows Server 2016. This is a fresh virtual environment with these packages installed:

```
Package    Version
---------- -------
pip        21.2.4
setuptools 57.5.0
SQLAlchemy 1.3.23
wheel      0.37.0
```

The full error:

```
(test_ibm_db_install) C:\py_envs>pip install --proxy <corporate proxy url>  ibm_db
Collecting ibm_db
  Using cached ibm_db-3.0.4.tar.gz (796 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\py_envs\test_ibm_db_install\scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\22\\pip-install-9tduy4h2\\ibm-db_3d58d3968e284c3c9c08010f6992f718\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\22\\pip-install-9tduy4h2\\ibm-db_3d58d3968e284c3c9c08010f6992f718\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\username\AppData\Local\Temp\22\pip-pip-egg-info-0jo9u79b'
         cwd: C:\Users\username\AppData\Local\Temp\22\pip-install-9tduy4h2\ibm-db_3d58d3968e284c3c9c08010f6992f718\
    Complete output (44 lines):
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
    Traceback (most recent call last):
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1346, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1257, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1303, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1252, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1012, in _send_output
        self.send(msg)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 952, in send
        self.connect()
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1419, in connect
        super().connect()
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 923, in connect
        self.sock = self._create_connection(
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\socket.py", line 843, in create_connection
        raise err
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\socket.py", line 831, in create_connection
        sock.connect(sa)
    TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\22\pip-install-9tduy4h2\ibm-db_3d58d3968e284c3c9c08010f6992f718\setup.py", line 240, in <module>
        file_stream = BytesIO(request.urlopen(url, context=context).read())
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
        response = self._open(req, data)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
        result = func(*args)
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1389, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1349, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/dc/7c/26c1eb0ce78689a6a6775337b43f498f8e901790ec0bafd6f24e2ef594af/ibm_db-3.0.4.tar.gz#sha256=2c6a806eb5071eacca5ddea0f0e4b8ad13594b1ba24dd57f00ea88708df289b3 (from https://pypi.org/simple/ibm-db/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by luisdelatorre012** [comment]
I'm seeing that the README addresses this. Sorry about that!
