### ISSUE TITLE
pip install fails on odbc driver download

### ISSUE THREAD

**Issue by clbsandwch** [ibmdb/python-ibmdb#695]
pip install ibm_db has been failing on download of odbc driver. 

Collecting ibm-db==3.1.0
  Downloading ibm_db-3.1.0.tar.gz (797 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: still running...
  Getting requirements to build wheel: finished with status 'error'
[91m  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpyiyjcgg8
       cwd: /tmp/pip-install-dr9_t81c/ibm-db_30f5e6d301334b9a91e76c95d5eb953b
  Complete output (30 lines):
  Detected 64-bit Python
  Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-c7fx23xw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-c7fx23xw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-c7fx23xw/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 240, in <module>
      file_stream = BytesIO(request.urlopen(url, context=context).read())
    File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
      response = meth(req, response)
    File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
      'http', request, response, code, msg, hdrs)
    File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
      return self._call_chain(*args)
    File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
      result = func(*args)
    File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by sxnguyen** [comment]
We get the same issue.  It appears the [site](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli) that host the CLI driver is down.  
There is a page that describe this behavior and the potential work-around.
Regrads,
Scott

**Comment by bimalkjha** [comment]
@clbsandwch This issue as for sort outage due to monthly site maintenance activity. It should be fixed now. Thanks.
