### ISSUE TITLE
Is Django 4.0, Python 3.10 supported?

### ISSUE THREAD

**Issue by dwadler** [ibmdb/python-ibmdb#715]
I just installed all of this including ibm_db and ibm_db_python.
Up until now I've been running with Python 3.7 and django 2.1.5 (in a separate environment)

When I ran 
python manage.py migrate
I received:
E:\dwacode\django\python3.10\myproj>python manage.py migrate
Traceback (most recent call last):
  File "d:\python10\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "d:\python10\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "d:\python10\lib\site-packages\ibm_db_django\base.py", line 53, in <module>
    import ibm_db_django.pybase as Base
  File "d:\python10\lib\site-packages\ibm_db_django\pybase.py", line 46, in <module>
    from django.utils.encoding import force_bytes, force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (d:\python10\lib\site-packages\django\utils\encoding.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\dwacode\django\python3.10\myproj\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "d:\python10\lib\site-packages\django\core\management\__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "d:\python10\lib\site-packages\django\core\management\__init__.py", line 401, in execute
    django.setup()
  File "d:\python10\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "d:\python10\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "d:\python10\lib\site-packages\django\apps\config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "d:\python10\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "d:\python10\lib\site-packages\django\contrib\auth\models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "d:\python10\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "d:\python10\lib\site-packages\django\db\models\base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "d:\python10\lib\site-packages\django\db\models\base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "d:\python10\lib\site-packages\django\db\models\options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "d:\python10\lib\site-packages\django\utils\connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "d:\python10\lib\site-packages\django\utils\connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "d:\python10\lib\site-packages\django\db\utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "d:\python10\lib\site-packages\django\db\utils.py", line 122, in load_backend
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: 'ibm_db_django' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by amukherjee28** [comment]
@dwadler Currently 4.0 is not support ibm_db_django driver. We have this in the pipeline.

**Comment by dwadler** [comment]
Thank you. I'm surprised that there are Django issues when ibm_db seems to be supported by Python 3.10.
