### ISSUE TITLE
Unable to build python ds driver on AIX / PPC 64

### ISSUE THREAD

**Issue by Anshu-Garg** [ibmdb/python-ibmdb#740]
**- Operating System Name:** AIX 7.1
**- db2level output from clidriver if in use:** 
 
NA

**- Target Db2 Server Version:** 

11.5.7 
 
**- Python Version: 2.7**

Python 2.7.10
 
- ibm_db version: 
 
Does not exist. Trying to build from source which is failing 

 
**- For non-Windows, output of below commands:**
  uname=> AIX
  uname -m ==> 0001637BD400
  uname -a ==> AIX ipas-vm25-152-028 1 7 0001637BD400

**- Value of below environment variables if set:**
 
```
_=/usr/bin/env
LANG=EN_US.UTF-8
HTTPS_PROXY=172.16.8.31:3128/
LOGIN=root
SSH_TTY=/dev/pts/1
CLCMD_PASSTHRU=1
PATH=/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/opt/IBM/ibm-java-ppc64-80/jre/bin:/opt/IBM/ibm-java-ppc64-80/bin:/usr/local/bin
LC_ALL=EN_US.UTF-8
FTP_PROXY=172.16.8.31:3128/
HTTP_PROXY=http://172.16.8.31:3128/
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
LC__FASTMSG=true
LOGNAME=root
MAIL=/usr/spool/mail/root
LOCPATH=/usr/lib/nls/loc
USER=root
AUTHSTATE=compat
https_proxy=http://172.16.8.31:3128/
SHELL=/usr/bin/ksh
ODMDIR=/etc/objrepos
JAVA_HOME=/opt/IBM/ibm-java-ppc64-80
HOME=/
NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com" ​If you also want to use a proxy to apt-get  you need to add this lines - Acquire::http::proxy "http://172.16.8.31:3128";
SSH_CONNECTION=172.16.254.8 60138 172.25.152.28 22
SSH_CLIENT=172.16.254.8 60138 22
TERM=xterm-256color
MAILMSG=[YOU HAVE NEW MAIL]
PWD=/python64/python-ibmdb-master/IBM_DB/ibm_db
TZ=UTC
http_proxy=http://172.16.8.31:3128/
ftp_proxy=http://172.16.8.31:3128/
A__z=! LOGNAME
NLSPATH=/usr/lib/nls/msg/%L/%N:/usr/lib/nls/msg/%L/%N.cat:/usr/lib/nls/msg/%l.%c/%N:/usr/lib/nls/msg/%l.%c/%N.cat
LIBPATH=/usr/lib

```

- Test script to reproduce the problem. **NA**
 
**- For installation related issue, complete output of `pip install ibm_db` command.**
NA

**Steps to Reproduce:**

git clone https://github.com/ibmdb/python-ibmdb.git
cd python-ibmdb/IBM_DB/ibm_db
python setup.py build
python setup.py install

Error is

```
# python setup.py build
Detected 32-bit Python
Detected platform = aix6, uname = 0001637BD400
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/aix32_odbc_cli.tar.gz
Traceback (most recent call last):
  File "setup.py", line 258, in <module>
    file_stream = BytesIO(request.urlopen(url, context=context).read())
  File "/opt/freeware/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/freeware/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/freeware/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/opt/freeware/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/freeware/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/opt/freeware/lib/python2.7/urllib2.py", line 1166, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/opt/freeware/lib/python2.7/httplib.py", line 1254, in __init__
    source_address)
  File "/opt/freeware/lib/python2.7/httplib.py", line 751, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/opt/freeware/lib/python2.7/httplib.py", line 793, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: '3128/'

```

**Comment by amukherjee28** [comment]
The Aix egg files were build and provided.
Also the issue was the XLC compiler not installed in the system.

Closing the issue as the required build were provided.
