### ISSUE TITLE
Windows -  Install Error urllib.error.HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by iammiddow** [ibmdb/python-ibmdb#745]
Windows 10 Pro 
PyCharm terminal 

Unable to install via pip into a virtualenv the ibm_db packaged most recent output below

(venv) PS C:XXXXXXXXXXXXX> pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Detected 64-bit Python
      Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
      Traceback (most recent call last):
        File "C:\Users\XXXXXXX\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\XXXXXXX\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\XXXXXXX\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-uafbrh5s\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-uafbrh5s\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\XXXXXXX\AppData\Local\Temp\pip-build-env-uafbrh5s\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 241, in <module>
          file_stream = BytesIO(request.urlopen(url, context=context).read())
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
          return opener.open(url, data, timeout)
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
          response = meth(req, response)
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
          response = self.parent.error(
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
          return self._call_chain(*args)
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
          result = func(*args)
        File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 500: Internal Server Error
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Jagadeepkosuri** [comment]
How to fix this problem @iammiddow

**Comment by DiogoR23** [comment]
@iammiddow How did you fix it?
