### ISSUE TITLE
Need Help Installing ibm_db or ibm_db_sa

### ISSUE THREAD

**Issue by Burn1n9m4n** [ibmdb/python-ibmdb#753]
- Operating System Name: Ubuntu
- Python Version: 3.8.10
- ibm_db version: 3.1.1
- For non-Windows, output of below commands:
  uname Linux
  uname -m x86_64
- For installation related issue, complete output of `pip install ibm_db` command.

Collecting ibm_db
  Using cached ibm_db-3.1.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Detected 64-bit Python
      Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
      Traceback (most recent call last):
        File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "/usr/lib/python3.8/http/client.py", line 1256, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
          self.send(msg)
        File "/usr/lib/python3.8/http/client.py", line 951, in send
          self.connect()
        File "/usr/lib/python3.8/http/client.py", line 1418, in connect
          super().connect()
        File "/usr/lib/python3.8/http/client.py", line 922, in connect
          self.sock = self._create_connection(
        File "/usr/lib/python3.8/socket.py", line 787, in create_connection
          for res in getaddrinfo(host, port, 0, SOCK_STREAM):
        File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
          for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
      socket.gaierror: [Errno -3] Temporary failure in name resolution

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/home/kaulv/repos/coursera_applied_data_science_capstone/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/kaulv/repos/coursera_applied_data_science_capstone/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/kaulv/repos/coursera_applied_data_science_capstone/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-brl7dyyn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-brl7dyyn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-brl7dyyn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 241, in <module>
          file_stream = BytesIO(request.urlopen(url, context=context).read())
        File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
          return opener.open(url, data, timeout)
        File "/usr/lib/python3.8/urllib/request.py", line 525, in open
          response = self._open(req, data)
        File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
          result = func(*args)
        File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Steps to Reproduce:

1. Just run pip install ibm_db or pip install ibm_db_sa

**Comment by Burn1n9m4n** [comment]
I should also mention that I'm trying to run this within WSL.

**Comment by bimalkjha** [comment]
@Burn1n9m4n It seems your firewall setting is blocking download of clidriver from ibm website. You can try manually downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz, untar it => you'll get clidriver directory. Now, run `export IBM_DB_HOME=<full_path_of_clidriver>` and then pip install ibm_db. It should work. Thanks.

**Comment by Burn1n9m4n** [comment]
Which directory is the clidriver? Is it the `ibm_db.py`?

**Comment by Burn1n9m4n** [comment]
I tried this:
export IBM_DB_HOME=/home/<my_username>/repos/ibm_db_sa-0.3.8/
pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpy7htnsmu/output.json'

**Comment by Burn1n9m4n** [comment]
This is really strange, I can't seem to connect to https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz via any of my browsers on my machine, but I can connect via mobile. So strange.

**Comment by amukherjee28** [comment]
You might consider setting the LIBRARY PATH.

Windows:
set LIB=%IBM_DB_HOME%/lib;%LIB%

AIX:
export LIBPATH=$IBM_DB_HOME/lib:$LIBPATH

MAC:
export DYLD_LIBRARY_PATH=$IBM_DB_HOME/lib:$DYLD_LIBRARY_PATH

Other platforms:
export LD_LIBRARY_PATH=$IBM_DB_HOME/lib:$LD_LIBRARY_PATH

**Comment by bimalkjha** [comment]
@Burn1n9m4n Please let us know if you are still facing this issue or issue is resolved after following the above update? Thanks.

**Comment by venkataramanam** [comment]
This file no more exists at the specified location ...
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

If you browse https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli, I do not see the file `linuxx64_odbc_cli.tar.gz`

**Comment by venkataramanam** [comment]
We happened to contact the concerned maintainer of the file server - https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
This should have been resolved now.

**Comment by sumosuzy** [comment]
Docker container for airflow
Python Version: 3.9.20
ibm_db version: 3.2.4

I am having the same exact problem when I run the docker file
```
#25 [21/23] RUN pip install     ibm_db
#25 2.003 Collecting ibm_db
#25 2.091   Downloading ibm_db-3.2.4.tar.gz (262 kB)
#25 2.279   Installing build dependencies: started
#25 10.41   Installing build dependencies: finished with status 'done'
#25 10.42   Getting requirements to build wheel: started
#25 30.82   Getting requirements to build wheel: finished with status 'error'
#25 30.83   error: subprocess-exited-with-error
#25 30.83   
25 30.83   × Getting requirements to build wheel did not run successfully.
25 30.83   │ exit code: 1
25 30.83   ╰─> [8 lines of output]
25 30.83       Detected 64-bit Python
25 30.83       Detected platform = linux, uname = x86_64
25 30.83       Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
25 30.83        Downloading DSDriver from url =  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
25 30.83       Pre-requisite check [which gcc] : Failed
#25 30.83       
#25 30.83       No Gcc installation detected.
#25 30.83       Please install gcc and continue with the installation of the ibm_db.
#25 30.83       [end of output]
```
Based on this thread I tried adding the following before the pip install but could not advert the download of linuxx64_odbc_cli.tar.gz.  I suspect my export command may be wrong cause I don't know what I am doing if there is a way around this.  Any help or suggestions would be appreciated.   I've tried from python 3.9 to 3.11 to get this to work.   I think i get the same issue with a lower version of ibm_db

```
run wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
run export IBM_DB_HOME=/home/airflow/repos/ibm_db-3.2.4/
```

**Comment by sumosuzy** [comment]
I got it to work.  I figured out what people were saying.   My pythhon I settled with was python 3.11.10 .  I ran this before the pip install

```
RUN wget https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz \
    && tar -xvzf linuxx64_odbc_cli.tar.gz -C /home/airflow/.local/lib/python3.11/site-packages \
    && export IBM_DB_HOME=/home/airflow/.local/lib/python3.11/site-packages/clidriver
```
