### ISSUE TITLE
Problem installing ibm_db on z/OS 2.5 and Python 3.10.5: No Gcc installation detected

### ISSUE THREAD

**Issue by plavjanik** [ibmdb/python-ibmdb#778]
- Operating System Name: z/OS 2.5
- db2level output from clidriver if in use: n/a
- Target Db2 Server Version:  Db2 for z/OS 12
- Python Version: IBM Enterprise Python 3.10.5
- ibm_db version:  3.1.3
- For non-Windows, output of below commands:
  uname # `OS/390`
  uname -m # `8561`
- Value of below environment variables if set:
  IBM_DB_HOME: `DB2.DB2C10`
  PATH: `/a/user/python_venv/db2/bin:/z/python310/usr/lpp/IBM/cyp/v3r10/pyz/bin`
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

```
$ pip3 install ibm_db --no-build-isolation -v
Using pip 22.2.2 from /a/user/python_venv/db2/lib/python3.10/site-packages/pip (python 3.10)
Collecting ibm_db
  Using cached ibm_db-3.1.3.tar.gz (1.4 MB)
  Running command Preparing metadata (pyproject.toml)
  oput 'DB2.DB2C10.SDSNMACS(DSNAO64C)' '/z/python310/tmp/pip-install-n3m75byk/ibm-db_c0393f09b3f74fb1aca5b73d73551bbe/libdsnao64c.x'
  Detected 64-bit Python
  Pre-requisite check [which gcc] : Failed

  No Gcc installation detected.
  Please install gcc and continue with the installation of the ibm_db.
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /a/user/python_venv/db2/bin/python3 /a/plape03/python_venv/db2/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /z/masserv/python310/tmp/tmp89iyi16i
  cwd: /z/python310/tmp/pip-install-n3m75byk/ibm-db_c0393f09b3f74fb1aca5b73d73551bbe
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Steps to Reproduce:

1. Follow the steps in https://github.com/ibmdb/python-ibmdb/blob/master/install.md with the most recent versions of Python on z/OS (3.10.5), z/OS (2.5), and ibm_db (3.1.3)
2. The pip command is: `pip3 install ibm_db --no-build-isolation -v`, same result is with `pip3 install ibm_db -v` too

**Comment by bimalkjha** [comment]
@plavjanik I think this check for gcc should be disabled for OS/390. We'll fix this issue. Thanks.

**Comment by bimalkjha** [comment]
@plavjanik You may install ibm_db using `pip install "ibm_db==3.1.1"` or `pip install "ibm_db==3.1.2"`. Thanks.

**Comment by plavjanik** [comment]
I have tried to install 3.1.1 and that worked well. Thanks :-)

**Comment by plavjanik** [comment]
For completeness, I have troubles with 3.1.2 too:

```
pip3 install ibm_db==3.1.2 --no-build-isolation -v
Using pip 22.1.2 from /a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip (python 3.10)
Collecting ibm_db==3.1.2
  Downloading ibm_db-3.1.2.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.1 MB/s eta 0:00:00
  Running command Preparing metadata (pyproject.toml)
  oput 'DB2.DB2C10.GA.RSU2206.SDSNMACS(DSNAO64C)' '/z/masserv/python310/tmp/pip-install-wrbea8hr/ibm-db_eeaa3e4200b04ab0b8095cc8afbe4714/libdsnao64c.x'
  Detected 64-bit Python

  No Gcc installation detected.
  Please install gcc and continue with the installation of the ibm_db.
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 497, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 526, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 328, in _call_hook
    data = compat.read_json(pjoin(td, 'output.json'))
  File "/a/plape03/python_venv/db2-3.10/lib/python3.10/site-packages/pip/_vendor/pep517/compat.py", line 16, in read_json
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 129] EDC5129I No such file or directory.: '/z/masserv/python310/tmp/tmpt_75f_mb/output.json'
```
