### ISSUE TITLE
Db2 z/OS: UnicodeDecodeError Exception thrown in conn_errormsg()

### ISSUE THREAD

**Issue by g-haas** [ibmdb/python-ibmdb#876]
### Problem description

Apparently, when trying to connect to a database server using `ibm_db.connect(),` `ibm_db` assumes error strings returned by the database server to be ASCII-encoded. This, however, may not be the case for Db2 on z/OS, as z/OS traditionally uses EBCDIC encoding. As a result, one cannot retrieve a detailed error description using `ibm_db.conn_errormsg()`.

Here’s what we did. We deliberately specified an invalid plan name in the ODBC config file and called `ibm_db.connect()`. Obviously, the connection failed. We then wanted to get some information about the error. Since in our opinion, it was too early for calling `ibm_db.stmt_errormsg()` at this point,  we tried `ibm_db.conn_errormsg()`. This call, however, resulted in an exception being thrown and the Python runtime complaining about some UnicodeDecodeError. This also happened if we did not even try to `print()` the error message – the call to the `ibm_db.conn_errormsg()` method by itself triggered the error.

Having a look at `ibm_db.c`, we noticed that `ibm_db_conn_errormsg` calls `StringOBJ_FromASCII()`. `ibm_db_stmt_errormsg` (backing `ibm_db.stmt_errormsg()` which works fine), in contrast, calls `StringOBJ_FromStr()`. Hence, we patched `ibm_db_conn_errormsg`, so that it calls `StringOBJ_FromStr()`, too, built our custom version of the `ibm_db` package and rerun our test. Of course, the connection still fails. However, now the call to `ibm_db.conn_errormsg()` succeeds and error details can be retrieved. After appropriate codepage translations, the text can even be printed.

So, why do the two `_errormsg()` methods treat the error messages they receive from the server differently? Is this on purpose?

### Environment

- Operating System Name: z/OS Unix System Services (USS)
- db2level output from clidriver if in use: ?
- Target Db2 Server Version: Db2 12 for z/OS, function level V12R1M510
- Python Version: 3.11.4
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname --> OS/390
  uname -m --> 8561

### db2-connection-test.py
This is the small example we tested with:
```python
import ibm_db

db_subsys = "xxxx"

conn = None
con_str = "DSN=DSN"+db_subsys

try:
    print( "Trying to connect...")
    conn = ibm_db.connect(con_str, None, None)

except:
    print("Connection failed with error %s" % ibm_db.conn_error())
    errmsg = ibm_db.conn_errormsg()
    print(str(errmsg.encode("IBM273").decode("IBM1047")))

    exit()
else:
    print ("Connection ok")
```
### odbc.ini
```
[COMMON]
MVSDEFAULTSSID=xxxx
FLOAT=IEEE
CURRENTAPPENSCH=ASCII
[xxxx]
AUTOCOMMIT=1
MVSATTACHTYPE=CAF
PLANNAME=xxxx
```
### Result (unpatched ibm_db)
Here's the output produced with an the stock ibm_db package:
```
Trying to connect...
Connection failed with error 51002
Traceback (most recent call last):
  File "db2-connection-test.py", line 11, in <module>
    conn = ibm_db.connect(con_str, None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "db2-connection-test.py", line 15, in <module>
    errmsg = ibm_db.conn_errormsg()
             ^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

### Result (patched ibm_db)
After applying the modifications mentioned above, the following output is yielded:
```
Trying to connect...
Connection failed with error 51002
{DB2 FOR OS/390}{ODBC DRIVER}  DSNT408I SQLCODE = -805, ERROR:  PACKAGE NAME [...]
```

**Comment by bimalkjha** [comment]
@g-haas When you specified `CURRENTAPPENSCH=ASCII` in db2cli.ini file, doesn't `{DB2 FOR OS/390}{ODBC DRIVER}` should return the error message in ASCII and not in EBCDIC? Could you please check why `CURRENTAPPENSCH=ASCII` is not effective for ODBC DRIVER? Thanks.

**Comment by pjfarleyiii** [comment]
I can confirm that in a z/OS USS shell at least for function ```ibm_db.stmt_errormsg()``` with ```CURRENTAPPENSCH=ASCII``` in z/OS file odbc.ini the returned error message is PARTLY in ASCII - the last 13 bytes or so are in IBM1047.  I had to code this in my test of the ibmdb functions to get the entire message printed to the terminal:

```
    try:
        stmt = ibm_db.exec_immediate(conn,sql_stmt)
    except:
        print("exec_immediate failed:")
        #print(ibm_db.stmt_errormsg())
        errmsg = str(ibm_db.stmt_errormsg().encode("ISO8859-1").decode("IBM1047"))
        errmsg = str(errmsg[:-13]) + str(errmsg[-13:].encode("IBM1047").decode("utf-8"))
        print(errmsg)
```

**Comment by bimalkjha** [comment]
@g-haas Could you please check tagging of your ODBC ini file?
`ls -lTE $DSNAOINI`

Please make sure tagging of your odbc.ini file is "binary" or "mixed":
chtag -b $DSNAOINI
or
chtag -m -c IBM-1047 $DSNAOINI
If file is tagged text (chtag -t -c IBM1047 $DSNAOINI) the S0C4 abend occurs. 

Please update us about the test result after tag correction. Thanks.

**Comment by jthyssenrocket** [comment]
@g-haas 

Python uses UTF-8 internally so ODBC must use ASCII or UNICODE, so there is no need to add encode/decode or patch ibm_db.c. 

We've found several customers with incorrect encoding/tagging of the odbc.ini file, which prevents ODBC from properly reading the file thus failing to honor your CURRENTAPPENSC=ASCII setting.

Can you post the encoding of your odbc.ini file?
chtag -p $DSNAOINI

Also, the -805 suggests the ODBC plans and packages are not bound.
Please check if Db2 sampe job SDSNSAMP(DSNTIJCL) has been run. This jobs binds the plan DSNACLI and a number of packages (DSNCLIC1, DSNCLIC2, etc etc) in collection DSNAOCLI.

**Comment by denisgaebler** [comment]
@jthyssenrocket I have worked with the customer and the -805 is intended to reproduce the error. This issue is not about fixing the -805 error, its about the encoding issue. Actually I would expect that even if CURRENTAPPENSC is not honoured, the code should be able to print an error message without the hazzle of several encode().decode() call chains.

**Comment by jthyssenrocket** [comment]
@denisgaebler 

I am working with ODBC z/OS development, and the conclusion right now is that it is **not** possible for the python driver to check if current application encoding scheme is set to ASCII or UNICODE before starting to issue queries. There is no ODBC/CLI API to check this on z/OS. 

Python is using unicode internally and does not expect to get error messages or data from ODBC back in EBCDIC. 

There are no encoding issues if the ODBC ini file is tagged as required and has CURRENTAPPENSC=ASCII or UNICODE.

**Comment by denisgaebler** [comment]
@jthyssenrocket So you cannot do a read from python with unicode as codeset parameter to check if its correctly tagged or throws an error on reading odbc.ini and evaluate the CURRENTAPPENVSC parm in there?
Something like:
````
# Read a file in 'UTF-8' encoding
f = open('odbc.ini', encoding='UTF-8')
print(f.read())
````
And catch a possible exception and throw it to the user before doing an actual call to Db2?

**Comment by jthyssenrocket** [comment]
@denisgaebler 

ibm_db is not reading any files. We issue ODBC/CLI calls to the C API implemented by ODBC for z/OS, so we need an C function we can call that returns the current application encoding scheme.

**Comment by denisgaebler** [comment]
@jthyssenrocket Maybe ibm_db should read odbc.ini to avoid all sorts of obscure errors that are caused by incorrectly tagged odbc.ini?

**Comment by jthyssenrocket** [comment]
It is outside the scope of ibm_db to read configuration files for the underlying drivers. We don't read db2dsdriver.cfg files on WIndows either. 

It is not a unique requirement for ibm_db. *Any* ODBC client that relies on a odbc.ini file in USS have this requirement. It doesn't matter if it is python, node.js, COBOL program, PL/I program, etc.

**Comment by g-haas** [comment]
> Python uses UTF-8 internally so ODBC must use ASCII or UNICODE, so there is no need to add encode/decode or patch ibm_db.c.

We originally used `CURRENTAPPENSCH=ASCII` in our `odbc.ini` (see above).

We just observed that, when setting `CURRENTAPPENSCH=UNICODE`, at least the original `Exception` thrown on `ibm_db.connect()` contains some useful and `print`-able information (this is not the case for `ASCII`). However, the call to `ibm_db.conn_errormsg()` in the `except` block still triggers another `UnicodeDecodeError`: 

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
If you look closely, it's a different one than in the original description (`[...] can't decode byte 0xc3 [...]` vs. `[...] can't decode byte 0xe4 [...]`).

> We've found several customers with incorrect encoding/tagging of the odbc.ini file, which prevents ODBC from properly reading the file thus failing to honor your CURRENTAPPENSC=ASCII setting.
> 
> Can you post the encoding of your odbc.ini file? chtag -p $DSNAOINI

Sure:
```
# chtag -p $DSNAOINI
b binary      T=off odbc.ini
```
Given the above observation regarding the slightly different `UnicodeDecodeError`s as well as the varying behavior with regard to the `Exception`s that are being thrown, I'd assume that our `odbc.ini` is being honored.
> 
> Also, the -805 suggests the ODBC plans and packages are not bound. Please check if Db2 sampe job SDSNSAMP(DSNTIJCL) has been run. This jobs binds the plan DSNACLI and a number of packages (DSNCLIC1, DSNCLIC2, etc etc) in collection DSNAOCLI.

Of course, you're right about the meaning of the `-805`. However, as indicated in the original description, we *deliberately specified an invalid plan name for test purposes*  :)

**Comment by g-haas** [comment]
> Does the same symptom appear in other functions, e.g ibm_db_conn_warn(), ibm_db_stmt_warn(), ibm_db_conn_error(), ibm_db_stmt_error(), and some other places?

- `ibm_db_conn_warn()`: ?
- `ibm_db_conn_error()`: no
- `ibm_db_stmt_warn()`: ?
- `ibm_db_stmt_error()`: no (tested with an existing plan specified in `odbc.ini` and invalid SQL statement)
- `ibm_db_stmt_errormsg()`: no (tested with an existing plan specified in `odbc.ini` and invalid SQL statement)

**Comment by jthyssenrocket** [comment]
We use the ODBC/CLI "W" (wide) APIs, e.g., SQLConnectW. The "W" APIs are supposed to return UTF-16 content always independent on CURRENTAPPENSC. See https://www.ibm.com/docs/en/db2-for-zos/13?topic=data-db2-odbc-unicode-support

Would it be possible to collect APPLTRACE=1 and DIAGTRACE=1, and upload here? There might be some invalid characters in the message returned by Db2.

**Comment by bimalkjha** [comment]
We  have documented [steps to install ibm_db on z/OS here](https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#inszos) in details. Please check it. Thanks.

**Comment by jthyssenrocket** [comment]
There is a deeper issue: we're using the SQLGetDiagRec API to retrieve error messages (not SQLGetDiagRecW UTF-16 API), so messages are returned in varying codepages. This is likely not an issue on distributed platforms, but on z/OS it appears we're getting a mix of EBCDIC, ASCII, and UNICODE error messages back, but our code assumes it is ASCII 

It seems it would be more robust to use the SQLGetDiagRecW which always returns UTF-16 error messages instead of assuming the message returned is in ASCII (and use StringOBJ_FromASCII() to convert it to python string). 

The recommendation from ODBC for z/OS development is also to use SQLGetDiagRecW. 

We are calling SQLGetDiagRec in lots of places, so this will be a larger change, though.

**Comment by bimalkjha** [comment]
Opened Jira bug https://jira.rocketsoftware.com/browse/DBC-14843 to fix this issue in ibm_db driver. Thanks.

**Comment by Earammak** [comment]
@g-haas Can you please share the update ?

**Comment by Earammak** [comment]
@g-haas, Could you please share the issue you are facing here with all the required information?

**Comment by Earammak** [comment]
@g-haas Closing this issue as there is no response from long time. Feel free to open the issue if you are still facing an issue providing all the details. 

Thanks
